# This R script implements decision tree classification using tree package.
# The decision tree classification aims to grow a tree by binary recursive partitioning
# using the predictor variables or features derived from image object statistics 
# generated by eCognition (at scale 10) and then choosing splits by land/forest cover types.
#
# Script By:      Jose Don T. De Alban
# Date Created:   09 May 2015
# Last Modified:  25 Feb 2016

# Set working directory
# Note: Need to change the path name as necessary
setwd("/Users/dondealban/Image Processing/Thesis/R/4 tree classification/")

# Load the required R libraries
library(tree)

# Read data, define variables, and store data in variables
dat2007 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2007.csv", header=TRUE, sep=",")
dat2008 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2008.csv", header=TRUE, sep=",")
dat2009 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2009.csv", header=TRUE, sep=",")
dat2010 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2010.csv", header=TRUE, sep=",")

# CASE 4: Polarisation + Texture

# Insert new standard variables for classification levels 1,2,3 for multi-year data

# Level1: land - water

# 2007
dat2007$LC1[dat2007$LCCode=="WNOW" | dat2007$LCCode=="WNRB" | dat2007$LCCode=="WNSS"] <- "WTR"
dat2007$LC1[dat2007$LCCode!="WNOW" & dat2007$LCCode!="WNRB" & dat2007$LCCode!="WNSS"] <- "LND"
# 2008
dat2008$LC1[dat2008$LCCode=="WNOW" | dat2008$LCCode=="WNRB" | dat2008$LCCode=="WNSS"] <- "WTR"
dat2008$LC1[dat2008$LCCode!="WNOW" & dat2008$LCCode!="WNRB" & dat2008$LCCode!="WNSS"] <- "LND"
# 2009
dat2009$LC1[dat2009$LCCode=="WNOW" | dat2009$LCCode=="WNRB" | dat2009$LCCode=="WNSS"] <- "WTR"
dat2009$LC1[dat2009$LCCode!="WNOW" & dat2009$LCCode!="WNRB" & dat2009$LCCode!="WNSS"] <- "LND"
# 2010
dat2010$LC1[dat2010$LCCode=="WNOW" | dat2010$LCCode=="WNRB" | dat2010$LCCode=="WNSS"] <- "WTR"
dat2010$LC1[dat2010$LCCode!="WNOW" & dat2010$LCCode!="WNRB" & dat2010$LCCode!="WNSS"] <- "LND"

# Level2: vegetation - non-vegetation

# 2007
dat2007$LC2[dat2007$LC1=="WTR"] <- "WTR"
dat2007$LC2[dat2007$LC1!="WTR" & dat2007$LCCode=="LNBU"] <- "NVG"
dat2007$LC2[dat2007$LC1!="WTR" & dat2007$LCCode!="LNBU"] <- "VEG"
# 2008
dat2008$LC2[dat2008$LC1=="WTR"] <- "WTR"
dat2008$LC2[dat2008$LC1!="WTR" & dat2008$LCCode=="LNBU"] <- "NVG"
dat2008$LC2[dat2008$LC1!="WTR" & dat2008$LCCode!="LNBU"] <- "VEG"
# 2009
dat2009$LC2[dat2009$LC1=="WTR"] <- "WTR"
dat2009$LC2[dat2009$LC1!="WTR" & dat2009$LCCode=="LNBU"] <- "NVG"
dat2009$LC2[dat2009$LC1!="WTR" & dat2009$LCCode!="LNBU"] <- "VEG"
# 2010
dat2010$LC2[dat2010$LC1=="WTR"] <- "WTR"
dat2010$LC2[dat2010$LC1!="WTR" & dat2010$LCCode=="LNBU"] <- "NVG"
dat2010$LC2[dat2010$LC1!="WTR" & dat2010$LCCode!="LNBU"] <- "VEG"

# Level3: forest - non-forest

# 2007
dat2007$LC3 <- "OOO"
dat2007$LC3[dat2007$LC2=="WTR"] <- "WTR"
dat2007$LC3[dat2007$LC2=="NVG"] <- "NVG"
dat2007$LC3[dat2007$LCCode=="LVGR" | dat2007$LCCode=="LVSH" | dat2007$LCCode=="LVWG"] <- "NFR"
dat2007$LC3[dat2007$LC3=="OOO"] <- "FOR"
# 2008
dat2008$LC3 <- "OOO"
dat2008$LC3[dat2008$LC2=="WTR"] <- "WTR"
dat2008$LC3[dat2008$LC2=="NVG"] <- "NVG"
dat2008$LC3[dat2008$LCCode=="LVGR" | dat2008$LCCode=="LVSH" | dat2008$LCCode=="LVWG"] <- "NFR"
dat2008$LC3[dat2008$LC3=="OOO"] <- "FOR"
# 2009
dat2009$LC3 <- "OOO"
dat2009$LC3[dat2009$LC2=="WTR"] <- "WTR"
dat2009$LC3[dat2009$LC2=="NVG"] <- "NVG"
dat2009$LC3[dat2009$LCCode=="LVGR" | dat2009$LCCode=="LVSH" | dat2009$LCCode=="LVWG"] <- "NFR"
dat2009$LC3[dat2009$LC3=="OOO"] <- "FOR"
# 2010
dat2010$LC3 <- "OOO"
dat2010$LC3[dat2010$LC2=="WTR"] <- "WTR"
dat2010$LC3[dat2010$LC2=="NVG"] <- "NVG"
dat2010$LC3[dat2010$LCCode=="LVGR" | dat2010$LCCode=="LVSH" | dat2010$LCCode=="LVWG"] <- "NFR"
dat2010$LC3[dat2010$LC3=="OOO"] <- "FOR"

# Insert new variables for remaining classification levels based on clustering dendrograms

# Level4: Node 8 Split

# 2007
dat2007$LC4 <- "OOO"
dat2007$LC4[dat2007$LC3=="WTR"] <- "WTR"
dat2007$LC4[dat2007$LC3=="NVG"] <- "NVG"
dat2007$LC4[dat2007$LC3=="NFR"] <- "NFR"
dat2007$LC4[dat2007$LCCode=="LVMG"] <- "MGF"
dat2007$LC4[dat2007$LC4=="OOO"] <- "FG7"
# 2008
dat2008$LC4 <- "OOO"
dat2008$LC4[dat2008$LC3=="WTR"] <- "WTR"
dat2008$LC4[dat2008$LC3=="NVG"] <- "NVG"
dat2008$LC4[dat2008$LC3=="NFR"] <- "NFR"
dat2008$LC4[dat2008$LCCode=="LVMG"] <- "MGF"
dat2008$LC4[dat2008$LC4=="OOO"] <- "FG7"
# 2009
dat2009$LC4 <- "OOO"
dat2009$LC4[dat2009$LC3=="WTR"] <- "WTR"
dat2009$LC4[dat2009$LC3=="NVG"] <- "NVG"
dat2009$LC4[dat2009$LC3=="NFR"] <- "NFR"
dat2009$LC4[dat2009$LCCode=="LVMG"] <- "MGF"
dat2009$LC4[dat2009$LC4=="OOO"] <- "FG7"
# 2010
dat2010$LC4 <- "OOO"
dat2010$LC4[dat2010$LC3=="WTR"] <- "WTR"
dat2010$LC4[dat2010$LC3=="NVG"] <- "NVG"
dat2010$LC4[dat2010$LC3=="NFR"] <- "NFR"
dat2010$LC4[dat2010$LCCode=="LVMG"] <- "MGF"
dat2010$LC4[dat2010$LC4=="OOO"] <- "FG7"

# Level5: Node 7 Split

# 2007
dat2007$LC5 <- "OOO"
dat2007$LC5[dat2007$LC4=="WTR"] <- "WTR"
dat2007$LC5[dat2007$LC4=="NVG"] <- "NVG"
dat2007$LC5[dat2007$LC4=="NFR"] <- "NFR"
dat2007$LC5[dat2007$LC4=="MGF"] <- "MGF"
dat2007$LC5[dat2007$LCCode=="FFPC"] <- "FPC"
dat2007$LC5[dat2007$LC5=="OOO"] <- "FG6"
# 2008
dat2008$LC5 <- "OOO"
dat2008$LC5[dat2008$LC4=="WTR"] <- "WTR"
dat2008$LC5[dat2008$LC4=="NVG"] <- "NVG"
dat2008$LC5[dat2008$LC4=="NFR"] <- "NFR"
dat2008$LC5[dat2008$LC4=="MGF"] <- "MGF"
dat2008$LC5[dat2008$LCCode=="FFPC"] <- "FPC"
dat2008$LC5[dat2008$LC5=="OOO"] <- "FG6"
# 2009
dat2009$LC5 <- "OOO"
dat2009$LC5[dat2009$LC4=="WTR"] <- "WTR"
dat2009$LC5[dat2009$LC4=="NVG"] <- "NVG"
dat2009$LC5[dat2009$LC4=="NFR"] <- "NFR"
dat2009$LC5[dat2009$LC4=="MGF"] <- "MGF"
dat2009$LC5[dat2009$LCCode=="FFPC"] <- "FPC"
dat2009$LC5[dat2009$LC5=="OOO"] <- "FG6"
# 2010
dat2010$LC5 <- "OOO"
dat2010$LC5[dat2010$LC4=="WTR"] <- "WTR"
dat2010$LC5[dat2010$LC4=="NVG"] <- "NVG"
dat2010$LC5[dat2010$LC4=="NFR"] <- "NFR"
dat2010$LC5[dat2010$LC4=="MGF"] <- "MGF"
dat2010$LC5[dat2010$LCCode=="FFPC"] <- "FPC"
dat2010$LC5[dat2010$LC5=="OOO"] <- "FG6"

# Level6: Node 6 Split

# 2007
dat2007$LC6 <- "OOO"
dat2007$LC6[dat2007$LC5=="WTR"] <- "WTR"
dat2007$LC6[dat2007$LC5=="NVG"] <- "NVG"
dat2007$LC6[dat2007$LC5=="NFR"] <- "NFR"
dat2007$LC6[dat2007$LC5=="MGF"] <- "MGF"
dat2007$LC6[dat2007$LC5=="FPC"] <- "FPC"
dat2007$LC6[dat2007$LCCode=="FCFC" | dat2007$LCCode=="FOFC" | dat2007$LCCode=="FOFM"] <- "FG4"
dat2007$LC6[dat2007$LC6=="OOO"] <- "FG5"
# 2008
dat2008$LC6 <- "OOO"
dat2008$LC6[dat2008$LC5=="WTR"] <- "WTR"
dat2008$LC6[dat2008$LC5=="NVG"] <- "NVG"
dat2008$LC6[dat2008$LC5=="NFR"] <- "NFR"
dat2008$LC6[dat2008$LC5=="MGF"] <- "MGF"
dat2008$LC6[dat2008$LC5=="FPC"] <- "FPC"
dat2008$LC6[dat2008$LCCode=="FCFC" | dat2008$LCCode=="FOFC"] <- "FG4"
dat2008$LC6[dat2008$LC6=="OOO"] <- "FG5"
# 2009
dat2009$LC6 <- "OOO"
dat2009$LC6[dat2009$LC5=="WTR"] <- "WTR"
dat2009$LC6[dat2009$LC5=="NVG"] <- "NVG"
dat2009$LC6[dat2009$LC5=="NFR"] <- "NFR"
dat2009$LC6[dat2009$LC5=="MGF"] <- "MGF"
dat2009$LC6[dat2009$LC5=="FPC"] <- "FPC"
dat2009$LC6[dat2009$LCCode=="FOFC"] <- "OFC"
dat2009$LC6[dat2009$LC6=="OOO"] <- "FG5"
# 2010
dat2010$LC6 <- "OOO"
dat2010$LC6[dat2010$LC5=="WTR"] <- "WTR"
dat2010$LC6[dat2010$LC5=="NVG"] <- "NVG"
dat2010$LC6[dat2010$LC5=="NFR"] <- "NFR"
dat2010$LC6[dat2010$LC5=="MGF"] <- "MGF"
dat2010$LC6[dat2010$LC5=="FPC"] <- "FPC"
dat2010$LC6[dat2010$LCCode=="FOFC"] <- "OFC"
dat2010$LC6[dat2010$LC6=="OOO"] <- "FG5"

# Level7: Node 5 Split

# 2007
dat2007$LC7 <- "OOO"
dat2007$LC7[dat2007$LC6=="WTR"] <- "WTR"
dat2007$LC7[dat2007$LC6=="NVG"] <- "NVG"
dat2007$LC7[dat2007$LC6=="NFR"] <- "NFR"
dat2007$LC7[dat2007$LC6=="MGF"] <- "MGF"
dat2007$LC7[dat2007$LC6=="FPC"] <- "FPC"
dat2007$LC7[dat2007$LC6=="FG4"] <- "FG4"
dat2007$LC7[dat2007$LCCode=="FCFM"] <- "CFM"
dat2007$LC7[dat2007$LC7=="OOO"] <- "FG3"
# 2008
dat2008$LC7 <- "OOO"
dat2008$LC7[dat2008$LC6=="WTR"] <- "WTR"
dat2008$LC7[dat2008$LC6=="NVG"] <- "NVG"
dat2008$LC7[dat2008$LC6=="NFR"] <- "NFR"
dat2008$LC7[dat2008$LC6=="MGF"] <- "MGF"
dat2008$LC7[dat2008$LC6=="FPC"] <- "FPC"
dat2008$LC7[dat2008$LC6=="FG4"] <- "FG4"
dat2008$LC7[dat2008$LCCode=="FCFB" | dat2008$LCCode=="FOFB"] <- "FG2"
dat2008$LC7[dat2008$LC7=="OOO"] <- "FG3"
# 2009
dat2009$LC7 <- "OOO"
dat2009$LC7[dat2009$LC6=="WTR"] <- "WTR"
dat2009$LC7[dat2009$LC6=="NVG"] <- "NVG"
dat2009$LC7[dat2009$LC6=="NFR"] <- "NFR"
dat2009$LC7[dat2009$LC6=="MGF"] <- "MGF"
dat2009$LC7[dat2009$LC6=="FPC"] <- "FPC"
dat2009$LC7[dat2009$LC6=="OFC"] <- "OFC"
dat2009$LC7[dat2009$LCCode=="FFPB" | dat2009$LCCode=="FCFC" | dat2009$LCCode=="FCFM"] <- "FG3"
dat2009$LC7[dat2009$LC7=="OOO"] <- "FG4"
# 2010
dat2010$LC7 <- "OOO"
dat2010$LC7[dat2010$LC6=="WTR"] <- "WTR"
dat2010$LC7[dat2010$LC6=="NVG"] <- "NVG"
dat2010$LC7[dat2010$LC6=="NFR"] <- "NFR"
dat2010$LC7[dat2010$LC6=="MGF"] <- "MGF"
dat2010$LC7[dat2010$LC6=="FPC"] <- "FPC"
dat2010$LC7[dat2010$LC6=="OFC"] <- "OFC"
dat2010$LC7[dat2010$LCCode=="FCFB" | dat2010$LCCode=="FOFB"] <- "FG1"
dat2010$LC7[dat2010$LC7=="OOO"] <- "FG4"

# Level8: Node 4 Split

# 2007
dat2007$LC8 <- "OOO"
dat2007$LC8[dat2007$LC7=="WTR"] <- "WTR"
dat2007$LC8[dat2007$LC7=="NVG"] <- "NVG"
dat2007$LC8[dat2007$LC7=="NFR"] <- "NFR"
dat2007$LC8[dat2007$LC7=="MGF"] <- "MGF"
dat2007$LC8[dat2007$LC7=="FPC"] <- "FPC"
dat2007$LC8[dat2007$LC7=="CFM"] <- "CFM"
dat2007$LC8[dat2007$LC7=="FG3"] <- "FG3"
dat2007$LC8[dat2007$LCCode=="FCFC"] <- "CFC"
dat2007$LC8[dat2007$LC8=="OOO"] <- "FG2"
# 2008
dat2008$LC8 <- "OOO"
dat2008$LC8[dat2008$LC7=="WTR"] <- "WTR"
dat2008$LC8[dat2008$LC7=="NVG"] <- "NVG"
dat2008$LC8[dat2008$LC7=="NFR"] <- "NFR"
dat2008$LC8[dat2008$LC7=="MGF"] <- "MGF"
dat2008$LC8[dat2008$LC7=="FPC"] <- "FPC"
dat2008$LC8[dat2008$LC7=="FG2"] <- "FG2"
dat2008$LC8[dat2008$LC7=="FG3"] <- "FG3"
dat2008$LC8[dat2008$LCCode=="FCFC"] <- "CFC"
dat2008$LC8[dat2008$LCCode=="FOFC"] <- "OFC"
# 2009
dat2009$LC8 <- "OOO"
dat2009$LC8[dat2009$LC7=="WTR"] <- "WTR"
dat2009$LC8[dat2009$LC7=="NVG"] <- "NVG"
dat2009$LC8[dat2009$LC7=="NFR"] <- "NFR"
dat2009$LC8[dat2009$LC7=="MGF"] <- "MGF"
dat2009$LC8[dat2009$LC7=="FPC"] <- "FPC"
dat2009$LC8[dat2009$LC7=="OFC"] <- "OFC"
dat2009$LC8[dat2009$LC7=="FG3"] <- "FG3"
dat2009$LC8[dat2009$LCCode=="FCFB"] <- "CFB"
dat2009$LC8[dat2009$LC8=="OOO"] <- "FG1"
# 2010
dat2010$LC8 <- "OOO"
dat2010$LC8[dat2010$LC7=="WTR"] <- "WTR"
dat2010$LC8[dat2010$LC7=="NVG"] <- "NVG"
dat2010$LC8[dat2010$LC7=="NFR"] <- "NFR"
dat2010$LC8[dat2010$LC7=="MGF"] <- "MGF"
dat2010$LC8[dat2010$LC7=="FPC"] <- "FPC"
dat2010$LC8[dat2010$LC7=="OFC"] <- "OFC"
dat2010$LC8[dat2010$LC7=="FG1"] <- "FG1"
dat2010$LC8[dat2010$LCCode=="FFPB"] <- "FPB"
dat2010$LC8[dat2010$LC8=="OOO"] <- "FG3"

# Level9: Node 3 Split

# 2007
dat2007$LC9 <- "OOO"
dat2007$LC9[dat2007$LC8=="WTR"] <- "WTR"
dat2007$LC9[dat2007$LC8=="NVG"] <- "NVG"
dat2007$LC9[dat2007$LC8=="NFR"] <- "NFR"
dat2007$LC9[dat2007$LC8=="MGF"] <- "MGF"
dat2007$LC9[dat2007$LC8=="FPC"] <- "FPC"
dat2007$LC9[dat2007$LC8=="CFM"] <- "CFM"
dat2007$LC9[dat2007$LC8=="CFC"] <- "CFC"
dat2007$LC9[dat2007$LC8=="FG2"] <- "FG2"
dat2007$LC9[dat2007$LCCode=="FCFB"] <- "CFB"
dat2007$LC9[dat2007$LC9=="OOO"] <- "FG1"
# 2008
dat2008$LC9 <- "OOO"
dat2008$LC9[dat2008$LC8=="WTR"] <- "WTR"
dat2008$LC9[dat2008$LC8=="NVG"] <- "NVG"
dat2008$LC9[dat2008$LC8=="NFR"] <- "NFR"
dat2008$LC9[dat2008$LC8=="MGF"] <- "MGF"
dat2008$LC9[dat2008$LC8=="FPC"] <- "FPC"
dat2008$LC9[dat2008$LC8=="CFC"] <- "CFC"
dat2008$LC9[dat2008$LC8=="OFC"] <- "OFC"
dat2008$LC9[dat2008$LC8=="FG2"] <- "FG2"
dat2008$LC9[dat2008$LCCode=="FCFM"] <- "CFM"
dat2008$LC9[dat2008$LC9=="OOO"] <- "FG1"
# 2009
dat2009$LC9 <- "OOO"
dat2009$LC9[dat2009$LC8=="WTR"] <- "WTR"
dat2009$LC9[dat2009$LC8=="NVG"] <- "NVG"
dat2009$LC9[dat2009$LC8=="NFR"] <- "NFR"
dat2009$LC9[dat2009$LC8=="MGF"] <- "MGF"
dat2009$LC9[dat2009$LC8=="FPC"] <- "FPC"
dat2009$LC9[dat2009$LC8=="OFC"] <- "OFC"
dat2009$LC9[dat2009$LC8=="CFB"] <- "CFB"
dat2009$LC9[dat2009$LC8=="FG1"] <- "FG1"
dat2009$LC9[dat2009$LCCode=="FFPB"] <- "FPB"
dat2009$LC9[dat2009$LC9=="OOO"] <- "FG2"
# 2010
dat2010$LC9 <- "OOO"
dat2010$LC9[dat2010$LC8=="WTR"] <- "WTR"
dat2010$LC9[dat2010$LC8=="NVG"] <- "NVG"
dat2010$LC9[dat2010$LC8=="NFR"] <- "NFR"
dat2010$LC9[dat2010$LC8=="MGF"] <- "MGF"
dat2010$LC9[dat2010$LC8=="FPC"] <- "FPC"
dat2010$LC9[dat2010$LC8=="OFC"] <- "OFC"
dat2010$LC9[dat2010$LC8=="FPB"] <- "FPB"
dat2010$LC9[dat2010$LC8=="FG1"] <- "FG1"
dat2010$LC9[dat2010$LCCode=="FCFC"] <- "CFC"
dat2010$LC9[dat2010$LC9=="OOO"] <- "FG2"

# Level10: Node 2 Split

# 2007
dat2007$LC10 <- "OOO"
dat2007$LC10[dat2007$LC9=="WTR"] <- "WTR"
dat2007$LC10[dat2007$LC9=="NVG"] <- "NVG"
dat2007$LC10[dat2007$LC9=="NFR"] <- "NFR"
dat2007$LC10[dat2007$LC9=="MGF"] <- "MGF"
dat2007$LC10[dat2007$LC9=="FPC"] <- "FPC"
dat2007$LC10[dat2007$LC9=="CFM"] <- "CFM"
dat2007$LC10[dat2007$LC9=="CFC"] <- "CFC"
dat2007$LC10[dat2007$LC9=="CFB"] <- "CFB"
dat2007$LC10[dat2007$LC9=="FG1"] <- "FG1"
dat2007$LC10[dat2007$LCCode=="FOFC"] <- "OFC"
dat2007$LC10[dat2007$LCCode=="FOFM"] <- "OFM"
# 2008
dat2008$LC10 <- "OOO"
dat2008$LC10[dat2008$LC9=="WTR"] <- "WTR"
dat2008$LC10[dat2008$LC9=="NVG"] <- "NVG"
dat2008$LC10[dat2008$LC9=="NFR"] <- "NFR"
dat2008$LC10[dat2008$LC9=="MGF"] <- "MGF"
dat2008$LC10[dat2008$LC9=="FPC"] <- "FPC"
dat2008$LC10[dat2008$LC9=="OFC"] <- "OFC"
dat2008$LC10[dat2008$LC9=="CFC"] <- "CFC"
dat2008$LC10[dat2008$LC9=="CFM"] <- "CFM"
dat2008$LC10[dat2008$LC9=="FG1"] <- "FG1"
dat2008$LC10[dat2008$LCCode=="FCFB"] <- "CFB"
dat2008$LC10[dat2008$LCCode=="FOFB"] <- "OFB"
# 2009
dat2009$LC10 <- "OOO"
dat2009$LC10[dat2009$LC9=="WTR"] <- "WTR"
dat2009$LC10[dat2009$LC9=="NVG"] <- "NVG"
dat2009$LC10[dat2009$LC9=="NFR"] <- "NFR"
dat2009$LC10[dat2009$LC9=="MGF"] <- "MGF"
dat2009$LC10[dat2009$LC9=="FPC"] <- "FPC"
dat2009$LC10[dat2009$LC9=="OFC"] <- "OFC"
dat2009$LC10[dat2009$LC9=="CFB"] <- "CFB"
dat2009$LC10[dat2009$LC9=="FPB"] <- "FPB"
dat2009$LC10[dat2009$LC9=="FG1"] <- "FG1"
dat2009$LC10[dat2009$LCCode=="FCFC"] <- "CFC"
dat2009$LC10[dat2009$LCCode=="FCFM"] <- "CFM"
# 2010
dat2010$LC10 <- "OOO"
dat2010$LC10[dat2010$LC9=="WTR"] <- "WTR"
dat2010$LC10[dat2010$LC9=="NVG"] <- "NVG"
dat2010$LC10[dat2010$LC9=="NFR"] <- "NFR"
dat2010$LC10[dat2010$LC9=="MGF"] <- "MGF"
dat2010$LC10[dat2010$LC9=="FPC"] <- "FPC"
dat2010$LC10[dat2010$LC9=="OFC"] <- "OFC"
dat2010$LC10[dat2010$LC9=="FPB"] <- "FPB"
dat2010$LC10[dat2010$LC9=="CFC"] <- "CFC"
dat2010$LC10[dat2010$LC9=="FG1"] <- "FG1"
dat2010$LC10[dat2010$LCCode=="FCFM"] <- "CFM"
dat2010$LC10[dat2010$LCCode=="FOFM"] <- "OFM"

# Level11: Node 1 Split

# 2007
dat2007$LC11 <- "OOO"
dat2007$LC11[dat2007$LC10=="WTR"] <- "WTR"
dat2007$LC11[dat2007$LC10=="NVG"] <- "NVG"
dat2007$LC11[dat2007$LC10=="NFR"] <- "NFR"
dat2007$LC11[dat2007$LC10=="MGF"] <- "MGF"
dat2007$LC11[dat2007$LC10=="FPC"] <- "FPC"
dat2007$LC11[dat2007$LC10=="CFM"] <- "CFM"
dat2007$LC11[dat2007$LC10=="CFC"] <- "CFC"
dat2007$LC11[dat2007$LC10=="CFB"] <- "CFB"
dat2007$LC11[dat2007$LC10=="OFC"] <- "OFC"
dat2007$LC11[dat2007$LC10=="OFM"] <- "OFM"
dat2007$LC11[dat2007$LCCode=="FOFB"] <- "OFB"
dat2007$LC11[dat2007$LCCode=="FFPB"] <- "FPB"
# 2008
dat2008$LC11 <- "OOO"
dat2008$LC11[dat2008$LC10=="WTR"] <- "WTR"
dat2008$LC11[dat2008$LC10=="NVG"] <- "NVG"
dat2008$LC11[dat2008$LC10=="NFR"] <- "NFR"
dat2008$LC11[dat2008$LC10=="MGF"] <- "MGF"
dat2008$LC11[dat2008$LC10=="FPC"] <- "FPC"
dat2008$LC11[dat2008$LC10=="CFC"] <- "CFC"
dat2008$LC11[dat2008$LC10=="OFC"] <- "OFC"
dat2008$LC11[dat2008$LC10=="CFM"] <- "CFM"
dat2008$LC11[dat2008$LC10=="CFB"] <- "CFB"
dat2008$LC11[dat2008$LC10=="OFB"] <- "OFB"
dat2008$LC11[dat2008$LCCode=="FOFM"] <- "OFM"
dat2008$LC11[dat2008$LCCode=="FFPB"] <- "FPB"
# 2009
dat2009$LC11 <- "OOO"
dat2009$LC11[dat2009$LC10=="WTR"] <- "WTR"
dat2009$LC11[dat2009$LC10=="NVG"] <- "NVG"
dat2009$LC11[dat2009$LC10=="NFR"] <- "NFR"
dat2009$LC11[dat2009$LC10=="MGF"] <- "MGF"
dat2009$LC11[dat2009$LC10=="FPC"] <- "FPC"
dat2009$LC11[dat2009$LC10=="OFC"] <- "OFC"
dat2009$LC11[dat2009$LC10=="CFB"] <- "CFB"
dat2009$LC11[dat2009$LC10=="FPB"] <- "FPB"
dat2009$LC11[dat2009$LC10=="CFC"] <- "CFC"
dat2009$LC11[dat2009$LC10=="CFM"] <- "CFM"
dat2009$LC11[dat2009$LCCode=="FOFB"] <- "OFB"
dat2009$LC11[dat2009$LCCode=="FOFM"] <- "OFM"
# 2010
dat2010$LC11 <- "OOO"
dat2010$LC11[dat2010$LC10=="WTR"] <- "WTR"
dat2010$LC11[dat2010$LC10=="NVG"] <- "NVG"
dat2010$LC11[dat2010$LC10=="NFR"] <- "NFR"
dat2010$LC11[dat2010$LC10=="MGF"] <- "MGF"
dat2010$LC11[dat2010$LC10=="FPC"] <- "FPC"
dat2010$LC11[dat2010$LC10=="OFC"] <- "OFC"
dat2010$LC11[dat2010$LC10=="FPB"] <- "FPB"
dat2010$LC11[dat2010$LC10=="CFC"] <- "CFC"
dat2010$LC11[dat2010$LC10=="CFM"] <- "CFM"
dat2010$LC11[dat2010$LC10=="OFM"] <- "OFM"
dat2010$LC11[dat2010$LCCode=="FCFB"] <- "CFB"
dat2010$LC11[dat2010$LCCode=="FOFB"] <- "OFB"

# Select observations per classification level and store selected data in variables

# 2007
dat2007.lc1  <- dat2007
dat2007.lc2  <- subset(dat2007, subset=(LC1=="LND"))
dat2007.lc3  <- subset(dat2007, subset=(LC2=="VEG"))
dat2007.lc4  <- subset(dat2007, subset=(LC3=="FOR"))
dat2007.lc5  <- subset(dat2007, subset=(LC4=="FG7"))
dat2007.lc6  <- subset(dat2007, subset=(LC5=="FG6"))
dat2007.lc7  <- subset(dat2007, subset=(LC6=="FG5"))
dat2007.lc8  <- subset(dat2007, subset=(LC7=="FG4"))
dat2007.lc9  <- subset(dat2007, subset=(LC8=="FG3"))
dat2007.lc10 <- subset(dat2007, subset=(LC9=="FG2"))
dat2007.lc11 <- subset(dat2007, subset=(LC10=="FG1"))
# 2008
dat2008.lc1  <- dat2008
dat2008.lc2  <- subset(dat2008, subset=(LC1=="LND"))
dat2008.lc3  <- subset(dat2008, subset=(LC2=="VEG"))
dat2008.lc4  <- subset(dat2008, subset=(LC3=="FOR"))
dat2008.lc5  <- subset(dat2008, subset=(LC4=="FG7"))
dat2008.lc6  <- subset(dat2008, subset=(LC5=="FG6"))
dat2008.lc7  <- subset(dat2008, subset=(LC6=="FG5"))
dat2008.lc8  <- subset(dat2008, subset=(LC7=="FG4"))
dat2008.lc9  <- subset(dat2008, subset=(LC8=="FG3"))
dat2008.lc10 <- subset(dat2008, subset=(LC9=="FG2"))
dat2008.lc11 <- subset(dat2008, subset=(LC10=="FG1"))
# 2009
dat2009.lc1  <- dat2009
dat2009.lc2  <- subset(dat2009, subset=(LC1=="LND"))
dat2009.lc3  <- subset(dat2009, subset=(LC2=="VEG"))
dat2009.lc4  <- subset(dat2009, subset=(LC3=="FOR"))
dat2009.lc5  <- subset(dat2009, subset=(LC4=="FG7"))
dat2009.lc6  <- subset(dat2009, subset=(LC5=="FG6"))
dat2009.lc7  <- subset(dat2009, subset=(LC6=="FG5"))
dat2009.lc8  <- subset(dat2009, subset=(LC7=="FG4"))
dat2009.lc9  <- subset(dat2009, subset=(LC8=="FG3"))
dat2009.lc10 <- subset(dat2009, subset=(LC9=="FG2"))
dat2009.lc11 <- subset(dat2009, subset=(LC10=="FG1"))
# 2010
dat2010.lc1  <- dat2010
dat2010.lc2  <- subset(dat2010, subset=(LC1=="LND"))
dat2010.lc3  <- subset(dat2010, subset=(LC2=="VEG"))
dat2010.lc4  <- subset(dat2010, subset=(LC3=="FOR"))
dat2010.lc5  <- subset(dat2010, subset=(LC4=="FG7"))
dat2010.lc6  <- subset(dat2010, subset=(LC5=="FG6"))
dat2010.lc7  <- subset(dat2010, subset=(LC6=="FG5"))
dat2010.lc8  <- subset(dat2010, subset=(LC7=="FG4"))
dat2010.lc9  <- subset(dat2010, subset=(LC8=="FG3"))
dat2010.lc10 <- subset(dat2010, subset=(LC9=="FG2"))
dat2010.lc11 <- subset(dat2010, subset=(LC10=="FG1"))

# Execute tree function using specified classification level and predictor variables

# 2007
tree2007.lc1  <- tree(factor(LC1)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2007.lc1)
tree2007.lc2  <- tree(factor(LC2)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2007.lc2)
tree2007.lc3  <- tree(factor(LC3)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2007.lc3)
tree2007.lc4  <- tree(factor(LC4)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2007.lc4)
tree2007.lc5  <- tree(factor(LC5)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2007.lc5)
tree2007.lc6  <- tree(factor(LC6)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2007.lc6)
tree2007.lc7  <- tree(factor(LC7)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2007.lc7)
tree2007.lc8  <- tree(factor(LC8)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2007.lc8)
tree2007.lc9  <- tree(factor(LC9)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2007.lc9)
tree2007.lc10 <- tree(factor(LC10) ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2007.lc10)
tree2007.lc11 <- tree(factor(LC11) ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2007.lc11)
# 2008
tree2008.lc1  <- tree(factor(LC1)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2008.lc1)
tree2008.lc2  <- tree(factor(LC2)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2008.lc2)
tree2008.lc3  <- tree(factor(LC3)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2008.lc3)
tree2008.lc4  <- tree(factor(LC4)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2008.lc4)
tree2008.lc5  <- tree(factor(LC5)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2008.lc5)
tree2008.lc6  <- tree(factor(LC6)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2008.lc6)
tree2008.lc7  <- tree(factor(LC7)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2008.lc7)
tree2008.lc8  <- tree(factor(LC8)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2008.lc8)
tree2008.lc9  <- tree(factor(LC9)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2008.lc9)
tree2008.lc10 <- tree(factor(LC10) ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2008.lc10)
tree2008.lc11 <- tree(factor(LC11) ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2008.lc11)
# 2009
tree2009.lc1  <- tree(factor(LC1)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2009.lc1)
tree2009.lc2  <- tree(factor(LC2)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2009.lc2)
tree2009.lc3  <- tree(factor(LC3)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2009.lc3)
tree2009.lc4  <- tree(factor(LC4)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2009.lc4)
tree2009.lc5  <- tree(factor(LC5)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2009.lc5)
tree2009.lc6  <- tree(factor(LC6)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2009.lc6)
tree2009.lc7  <- tree(factor(LC7)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2009.lc7)
tree2009.lc8  <- tree(factor(LC8)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2009.lc8)
tree2009.lc9  <- tree(factor(LC9)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2009.lc9)
tree2009.lc10 <- tree(factor(LC10) ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2009.lc10)
tree2009.lc11 <- tree(factor(LC11) ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2009.lc11)
# 2010
tree2010.lc1  <- tree(factor(LC1)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2010.lc1)
tree2010.lc2  <- tree(factor(LC2)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2010.lc2)
tree2010.lc3  <- tree(factor(LC3)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2010.lc3)
tree2010.lc4  <- tree(factor(LC4)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2010.lc4)
tree2010.lc5  <- tree(factor(LC5)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2010.lc5)
tree2010.lc6  <- tree(factor(LC6)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2010.lc6)
tree2010.lc7  <- tree(factor(LC7)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2010.lc7)
tree2010.lc8  <- tree(factor(LC8)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2010.lc8)
tree2010.lc9  <- tree(factor(LC9)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2010.lc9)
tree2010.lc10 <- tree(factor(LC10) ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2010.lc10)
tree2010.lc11 <- tree(factor(LC11) ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT + GLCMAngHH + GLCMAngHV + GLCMAngRAT + GLCMConHH + GLCMConHV + GLCMConRAT + GLCMCorHH + GLCMCorHV + GLCMCorRAT + GLCMDisHH + GLCMDisHV + GLCMDisRAT + GLCMEntHH + GLCMEntHV + GLCMEntRAT + GLCMHomHH + GLCMHomHV + GLCMHomRAT + GLCMMnHH + GLCMMnHV + GLCMMnRAT + GLCMSDHH + GLCMSDHV + GLCMSDRAT, dat2010.lc11)

# Perform k-fold cross-validation for each classification level of multi-year data

# 2007
cv2007.lc1  <- cv.tree(tree2007.lc1)
cv2007.lc2  <- cv.tree(tree2007.lc2)
cv2007.lc3  <- cv.tree(tree2007.lc3)
cv2007.lc4  <- cv.tree(tree2007.lc4)
cv2007.lc5  <- cv.tree(tree2007.lc5)
cv2007.lc6  <- cv.tree(tree2007.lc6)
cv2007.lc7  <- cv.tree(tree2007.lc7)
cv2007.lc8  <- cv.tree(tree2007.lc8)
cv2007.lc9  <- cv.tree(tree2007.lc9)
cv2007.lc10 <- cv.tree(tree2007.lc10)
cv2007.lc11 <- cv.tree(tree2007.lc11)
# 2008
cv2008.lc1  <- cv.tree(tree2008.lc1)
cv2008.lc2  <- cv.tree(tree2008.lc2)
cv2008.lc3  <- cv.tree(tree2008.lc3)
cv2008.lc4  <- cv.tree(tree2008.lc4)
cv2008.lc5  <- cv.tree(tree2008.lc5)
cv2008.lc6  <- cv.tree(tree2008.lc6)
cv2008.lc7  <- cv.tree(tree2008.lc7)
cv2008.lc8  <- cv.tree(tree2008.lc8)
cv2008.lc9  <- cv.tree(tree2008.lc9)
cv2008.lc10 <- cv.tree(tree2008.lc10)
cv2008.lc11 <- cv.tree(tree2008.lc11)
# 2009
cv2009.lc1  <- cv.tree(tree2009.lc1)
cv2009.lc2  <- cv.tree(tree2009.lc2)
cv2009.lc3  <- cv.tree(tree2009.lc3)
cv2009.lc4  <- cv.tree(tree2009.lc4)
cv2009.lc5  <- cv.tree(tree2009.lc5)
cv2009.lc6  <- cv.tree(tree2009.lc6)
cv2009.lc7  <- cv.tree(tree2009.lc7)
cv2009.lc8  <- cv.tree(tree2009.lc8)
cv2009.lc9  <- cv.tree(tree2009.lc9)
cv2009.lc10 <- cv.tree(tree2009.lc10)
cv2009.lc11 <- cv.tree(tree2009.lc11)
# 2010
cv2010.lc1  <- cv.tree(tree2010.lc1)
cv2010.lc2  <- cv.tree(tree2010.lc2)
cv2010.lc3  <- cv.tree(tree2010.lc3)
cv2010.lc4  <- cv.tree(tree2010.lc4)
cv2010.lc5  <- cv.tree(tree2010.lc5)
cv2010.lc6  <- cv.tree(tree2010.lc6)
cv2010.lc7  <- cv.tree(tree2010.lc7)
cv2010.lc8  <- cv.tree(tree2010.lc8)
cv2010.lc9  <- cv.tree(tree2010.lc9)
cv2010.lc10 <- cv.tree(tree2010.lc10)
cv2010.lc11 <- cv.tree(tree2010.lc11)

# Extract smallest/best deviance from k-fold cross-validation results of multi-year data

# 2007
best2007.lc1  <- cv2007.lc1$size[which(cv2007.lc1$dev==min(cv2007.lc1$dev))]
best2007.lc2  <- cv2007.lc2$size[which(cv2007.lc2$dev==min(cv2007.lc2$dev))]
best2007.lc3  <- cv2007.lc3$size[which(cv2007.lc3$dev==min(cv2007.lc3$dev))]
best2007.lc4  <- cv2007.lc4$size[which(cv2007.lc4$dev==min(cv2007.lc4$dev))]
best2007.lc5  <- cv2007.lc5$size[which(cv2007.lc5$dev==min(cv2007.lc5$dev))]
best2007.lc6  <- cv2007.lc6$size[which(cv2007.lc6$dev==min(cv2007.lc6$dev))]
best2007.lc7  <- cv2007.lc7$size[which(cv2007.lc7$dev==min(cv2007.lc7$dev))]
best2007.lc8  <- cv2007.lc8$size[which(cv2007.lc8$dev==min(cv2007.lc8$dev))]
best2007.lc9  <- cv2007.lc9$size[which(cv2007.lc9$dev==min(cv2007.lc9$dev))]
best2007.lc10 <- cv2007.lc10$size[which(cv2007.lc10$dev==min(cv2007.lc10$dev))]
best2007.lc11 <- cv2007.lc11$size[which(cv2007.lc11$dev==min(cv2007.lc11$dev))]
# 2008
best2008.lc1  <- cv2008.lc1$size[which(cv2008.lc1$dev==min(cv2008.lc1$dev))]
best2008.lc2  <- cv2008.lc2$size[which(cv2008.lc2$dev==min(cv2008.lc2$dev))]
best2008.lc3  <- cv2008.lc3$size[which(cv2008.lc3$dev==min(cv2008.lc3$dev))]
best2008.lc4  <- cv2008.lc4$size[which(cv2008.lc4$dev==min(cv2008.lc4$dev))]
best2008.lc5  <- cv2008.lc5$size[which(cv2008.lc5$dev==min(cv2008.lc5$dev))]
best2008.lc6  <- cv2008.lc6$size[which(cv2008.lc6$dev==min(cv2008.lc6$dev))]
best2008.lc7  <- cv2008.lc7$size[which(cv2008.lc7$dev==min(cv2008.lc7$dev))]
best2008.lc8  <- cv2008.lc8$size[which(cv2008.lc8$dev==min(cv2008.lc8$dev))]
best2008.lc9  <- cv2008.lc9$size[which(cv2008.lc9$dev==min(cv2008.lc9$dev))]
best2008.lc10 <- cv2008.lc10$size[which(cv2008.lc10$dev==min(cv2008.lc10$dev))]
best2008.lc11 <- cv2008.lc11$size[which(cv2008.lc11$dev==min(cv2008.lc11$dev))]
# 2009
best2009.lc1  <- cv2009.lc1$size[which(cv2009.lc1$dev==min(cv2009.lc1$dev))]
best2009.lc2  <- cv2009.lc2$size[which(cv2009.lc2$dev==min(cv2009.lc2$dev))]
best2009.lc3  <- cv2009.lc3$size[which(cv2009.lc3$dev==min(cv2009.lc3$dev))]
best2009.lc4  <- cv2009.lc4$size[which(cv2009.lc4$dev==min(cv2009.lc4$dev))]
best2009.lc5  <- cv2009.lc5$size[which(cv2009.lc5$dev==min(cv2009.lc5$dev))]
best2009.lc6  <- cv2009.lc6$size[which(cv2009.lc6$dev==min(cv2009.lc6$dev))]
best2009.lc7  <- cv2009.lc7$size[which(cv2009.lc7$dev==min(cv2009.lc7$dev))]
best2009.lc8  <- cv2009.lc8$size[which(cv2009.lc8$dev==min(cv2009.lc8$dev))]
best2009.lc9  <- cv2009.lc9$size[which(cv2009.lc9$dev==min(cv2009.lc9$dev))]
best2009.lc10 <- cv2009.lc10$size[which(cv2009.lc10$dev==min(cv2009.lc10$dev))]
best2009.lc11 <- cv2009.lc11$size[which(cv2009.lc11$dev==min(cv2009.lc11$dev))]
# 2010
best2010.lc1  <- cv2010.lc1$size[which(cv2010.lc1$dev==min(cv2010.lc1$dev))]
best2010.lc2  <- cv2010.lc2$size[which(cv2010.lc2$dev==min(cv2010.lc2$dev))]
best2010.lc3  <- cv2010.lc3$size[which(cv2010.lc3$dev==min(cv2010.lc3$dev))]
best2010.lc4  <- cv2010.lc4$size[which(cv2010.lc4$dev==min(cv2010.lc4$dev))]
best2010.lc5  <- cv2010.lc5$size[which(cv2010.lc5$dev==min(cv2010.lc5$dev))]
best2010.lc6  <- cv2010.lc6$size[which(cv2010.lc6$dev==min(cv2010.lc6$dev))]
best2010.lc7  <- cv2010.lc7$size[which(cv2010.lc7$dev==min(cv2010.lc7$dev))]
best2010.lc8  <- cv2010.lc8$size[which(cv2010.lc8$dev==min(cv2010.lc8$dev))]
best2010.lc9  <- cv2010.lc9$size[which(cv2010.lc9$dev==min(cv2010.lc9$dev))]
best2010.lc10 <- cv2010.lc10$size[which(cv2010.lc10$dev==min(cv2010.lc10$dev))]
best2010.lc11 <- cv2010.lc11$size[which(cv2010.lc11$dev==min(cv2010.lc11$dev))]

# Prune the tree model using smallest/best deviance from cross-validation results
# (Note: the number of leafs will be no more than the smallest/best deviance)

# 2007
prune2007.lc1 <- prune.misclass(tree2007.lc1, best=best2007.lc1)
prune2007.lc2 <- prune.misclass(tree2007.lc2, best=best2007.lc2)
prune2007.lc3 <- prune.misclass(tree2007.lc3, best=best2007.lc3)
prune2007.lc4 <- prune.misclass(tree2007.lc4, best=best2007.lc4)
prune2007.lc5 <- prune.misclass(tree2007.lc5, best=best2007.lc5)
prune2007.lc6 <- prune.misclass(tree2007.lc6, best=best2007.lc6)
prune2007.lc7 <- prune.misclass(tree2007.lc7, best=best2007.lc7)
prune2007.lc8 <- prune.misclass(tree2007.lc8, best=best2007.lc8)
prune2007.lc9 <- prune.misclass(tree2007.lc9, best=best2007.lc9)
prune2007.lc10 <- prune.misclass(tree2007.lc10, best=best2007.lc10)
prune2007.lc11 <- prune.misclass(tree2007.lc11, best=best2007.lc11)
# 2008
prune2008.lc1 <- prune.misclass(tree2008.lc1, best=best2008.lc1)
prune2008.lc2 <- prune.misclass(tree2008.lc2, best=best2008.lc2)
prune2008.lc3 <- prune.misclass(tree2008.lc3, best=best2008.lc3)
prune2008.lc4 <- prune.misclass(tree2008.lc4, best=best2008.lc4)
prune2008.lc5 <- prune.misclass(tree2008.lc5, best=best2008.lc5)
prune2008.lc6 <- prune.misclass(tree2008.lc6, best=best2008.lc6)
prune2008.lc7 <- prune.misclass(tree2008.lc7, best=best2008.lc7)
prune2008.lc8 <- prune.misclass(tree2008.lc8, best=best2008.lc8)
prune2008.lc9 <- prune.misclass(tree2008.lc9, best=best2008.lc9)
prune2008.lc10 <- prune.misclass(tree2008.lc10, best=best2008.lc10)
prune2008.lc11 <- prune.misclass(tree2008.lc11, best=best2008.lc11)
# 2009
prune2009.lc1 <- prune.misclass(tree2009.lc1, best=best2009.lc1)
prune2009.lc2 <- prune.misclass(tree2009.lc2, best=best2009.lc2)
prune2009.lc3 <- prune.misclass(tree2009.lc3, best=best2009.lc3)
prune2009.lc4 <- prune.misclass(tree2009.lc4, best=best2009.lc4)
prune2009.lc5 <- prune.misclass(tree2009.lc5, best=best2009.lc5)
prune2009.lc6 <- prune.misclass(tree2009.lc6, best=best2009.lc6)
prune2009.lc7 <- prune.misclass(tree2009.lc7, best=best2009.lc7)
prune2009.lc8 <- prune.misclass(tree2009.lc8, best=best2009.lc8)
prune2009.lc9 <- prune.misclass(tree2009.lc9, best=best2009.lc9)
prune2009.lc10 <- prune.misclass(tree2009.lc10, best=best2009.lc10)
prune2009.lc11 <- prune.misclass(tree2009.lc11, best=best2009.lc11)
# 2010
prune2010.lc1 <- prune.misclass(tree2010.lc1, best=best2010.lc1)
prune2010.lc2 <- prune.misclass(tree2010.lc2, best=best2010.lc2)
prune2010.lc3 <- prune.misclass(tree2010.lc3, best=best2010.lc3)
prune2010.lc4 <- prune.misclass(tree2010.lc4, best=best2010.lc4)
prune2010.lc5 <- prune.misclass(tree2010.lc5, best=best2010.lc5)
prune2010.lc6 <- prune.misclass(tree2010.lc6, best=best2010.lc6)
prune2010.lc7 <- prune.misclass(tree2010.lc7, best=best2010.lc7)
prune2010.lc8 <- prune.misclass(tree2010.lc8, best=best2010.lc8)
prune2010.lc9 <- prune.misclass(tree2010.lc9, best=best2010.lc9)
prune2010.lc10 <- prune.misclass(tree2010.lc10, best=best2010.lc10)
prune2010.lc11 <- prune.misclass(tree2010.lc11, best=best2010.lc11)

# Plot cross-validation graph and save as PDF file

# 2007
pdf("output-2007-cv-lc1.pdf", width=7, height=5.5)
plot(cv.tree(tree2007.lc1))
dev.off()
pdf("output-2007-cv-lc2.pdf", width=7, height=5.5)
plot(cv.tree(tree2007.lc2))
dev.off()
pdf("output-2007-cv-lc3.pdf", width=7, height=5.5)
plot(cv.tree(tree2007.lc3))
dev.off()
pdf("output-2007-cv-lc4.pdf", width=7, height=5.5)
plot(cv.tree(tree2007.lc4))
dev.off()
pdf("output-2007-cv-lc5.pdf", width=7, height=5.5)
plot(cv.tree(tree2007.lc5))
dev.off()
pdf("output-2007-cv-lc6.pdf", width=7, height=5.5)
plot(cv.tree(tree2007.lc6))
dev.off()
pdf("output-2007-cv-lc7.pdf", width=7, height=5.5)
plot(cv.tree(tree2007.lc7))
dev.off()
pdf("output-2007-cv-lc8.pdf", width=7, height=5.5)
plot(cv.tree(tree2007.lc8))
dev.off()
pdf("output-2007-cv-lc9.pdf", width=7, height=5.5)
plot(cv.tree(tree2007.lc9))
dev.off()
pdf("output-2007-cv-lc10.pdf", width=7, height=5.5)
plot(cv.tree(tree2007.lc10))
dev.off()
pdf("output-2007-cv-lc11.pdf", width=7, height=5.5)
plot(cv.tree(tree2007.lc11))
dev.off()
# 2008
pdf("output-2008-cv-lc1.pdf", width=7, height=5.5)
plot(cv.tree(tree2008.lc1))
dev.off()
pdf("output-2008-cv-lc2.pdf", width=7, height=5.5)
plot(cv.tree(tree2008.lc2))
dev.off()
pdf("output-2008-cv-lc3.pdf", width=7, height=5.5)
plot(cv.tree(tree2008.lc3))
dev.off()
pdf("output-2008-cv-lc4.pdf", width=7, height=5.5)
plot(cv.tree(tree2008.lc4))
dev.off()
pdf("output-2008-cv-lc5.pdf", width=7, height=5.5)
plot(cv.tree(tree2008.lc5))
dev.off()
pdf("output-2008-cv-lc6.pdf", width=7, height=5.5)
plot(cv.tree(tree2008.lc6))
dev.off()
pdf("output-2008-cv-lc7.pdf", width=7, height=5.5)
plot(cv.tree(tree2008.lc7))
dev.off()
pdf("output-2008-cv-lc8.pdf", width=7, height=5.5)
plot(cv.tree(tree2008.lc8))
dev.off()
pdf("output-2008-cv-lc9.pdf", width=7, height=5.5)
plot(cv.tree(tree2008.lc9))
dev.off()
pdf("output-2008-cv-lc10.pdf", width=7, height=5.5)
plot(cv.tree(tree2008.lc10))
dev.off()
pdf("output-2008-cv-lc11.pdf", width=7, height=5.5)
plot(cv.tree(tree2008.lc11))
dev.off()
# 2009
pdf("output-2009-cv-lc1.pdf", width=7, height=5.5)
plot(cv.tree(tree2009.lc1))
dev.off()
pdf("output-2009-cv-lc2.pdf", width=7, height=5.5)
plot(cv.tree(tree2009.lc2))
dev.off()
pdf("output-2009-cv-lc3.pdf", width=7, height=5.5)
plot(cv.tree(tree2009.lc3))
dev.off()
pdf("output-2009-cv-lc4.pdf", width=7, height=5.5)
plot(cv.tree(tree2009.lc4))
dev.off()
pdf("output-2009-cv-lc5.pdf", width=7, height=5.5)
plot(cv.tree(tree2009.lc5))
dev.off()
pdf("output-2009-cv-lc6.pdf", width=7, height=5.5)
plot(cv.tree(tree2009.lc6))
dev.off()
pdf("output-2009-cv-lc7.pdf", width=7, height=5.5)
plot(cv.tree(tree2009.lc7))
dev.off()
pdf("output-2009-cv-lc8.pdf", width=7, height=5.5)
plot(cv.tree(tree2009.lc8))
dev.off()
pdf("output-2009-cv-lc9.pdf", width=7, height=5.5)
plot(cv.tree(tree2009.lc9))
dev.off()
pdf("output-2009-cv-lc10.pdf", width=7, height=5.5)
plot(cv.tree(tree2009.lc10))
dev.off()
pdf("output-2009-cv-lc11.pdf", width=7, height=5.5)
plot(cv.tree(tree2009.lc11))
dev.off()
# 2010
pdf("output-2010-cv-lc1.pdf", width=7, height=5.5)
plot(cv.tree(tree2010.lc1))
dev.off()
pdf("output-2010-cv-lc2.pdf", width=7, height=5.5)
plot(cv.tree(tree2010.lc2))
dev.off()
pdf("output-2010-cv-lc3.pdf", width=7, height=5.5)
plot(cv.tree(tree2010.lc3))
dev.off()
pdf("output-2010-cv-lc4.pdf", width=7, height=5.5)
plot(cv.tree(tree2010.lc4))
dev.off()
pdf("output-2010-cv-lc5.pdf", width=7, height=5.5)
plot(cv.tree(tree2010.lc5))
dev.off()
pdf("output-2010-cv-lc6.pdf", width=7, height=5.5)
plot(cv.tree(tree2010.lc6))
dev.off()
pdf("output-2010-cv-lc7.pdf", width=7, height=5.5)
plot(cv.tree(tree2010.lc7))
dev.off()
pdf("output-2010-cv-lc8.pdf", width=7, height=5.5)
plot(cv.tree(tree2010.lc8))
dev.off()
pdf("output-2010-cv-lc9.pdf", width=7, height=5.5)
plot(cv.tree(tree2010.lc9))
dev.off()
pdf("output-2010-cv-lc10.pdf", width=7, height=5.5)
plot(cv.tree(tree2010.lc10))
dev.off()
pdf("output-2010-cv-lc11.pdf", width=7, height=5.5)
plot(cv.tree(tree2010.lc11))
dev.off()

# Generate tree summary and misclassification statistics (overfitted) and save as TXT file

# 2007
sink("output-2007-tree-overfit-summary-lc1.txt", append=FALSE, split=TRUE)
print(tree2007.lc1)
print(summary(tree2007.lc1))
print(misclass.tree(tree2007.lc1, detail=TRUE))
sink()
sink("output-2007-tree-overfit-summary-lc2.txt", append=FALSE, split=TRUE)
print(tree2007.lc2)
print(summary(tree2007.lc2))
print(misclass.tree(tree2007.lc2, detail=TRUE))
sink()
sink("output-2007-tree-overfit-summary-lc3.txt", append=FALSE, split=TRUE)
print(tree2007.lc3)
print(summary(tree2007.lc3))
print(misclass.tree(tree2007.lc3, detail=TRUE))
sink()
sink("output-2007-tree-overfit-summary-lc4.txt", append=FALSE, split=TRUE)
print(tree2007.lc4)
print(summary(tree2007.lc4))
print(misclass.tree(tree2007.lc4, detail=TRUE))
sink()
sink("output-2007-tree-overfit-summary-lc5.txt", append=FALSE, split=TRUE)
print(tree2007.lc5)
print(summary(tree2007.lc5))
print(misclass.tree(tree2007.lc5, detail=TRUE))
sink()
sink("output-2007-tree-overfit-summary-lc6.txt", append=FALSE, split=TRUE)
print(tree2007.lc6)
print(summary(tree2007.lc6))
print(misclass.tree(tree2007.lc6, detail=TRUE))
sink()
sink("output-2007-tree-overfit-summary-lc7.txt", append=FALSE, split=TRUE)
print(tree2007.lc7)
print(summary(tree2007.lc7))
print(misclass.tree(tree2007.lc7, detail=TRUE))
sink()
sink("output-2007-tree-overfit-summary-lc8.txt", append=FALSE, split=TRUE)
print(tree2007.lc8)
print(summary(tree2007.lc8))
print(misclass.tree(tree2007.lc8, detail=TRUE))
sink()
sink("output-2007-tree-overfit-summary-lc9.txt", append=FALSE, split=TRUE)
print(tree2007.lc9)
print(summary(tree2007.lc9))
print(misclass.tree(tree2007.lc9, detail=TRUE))
sink()
sink("output-2007-tree-overfit-summary-lc10.txt", append=FALSE, split=TRUE)
print(tree2007.lc10)
print(summary(tree2007.lc10))
print(misclass.tree(tree2007.lc10, detail=TRUE))
sink()
sink("output-2007-tree-overfit-summary-lc11.txt", append=FALSE, split=TRUE)
print(tree2007.lc11)
print(summary(tree2007.lc11))
print(misclass.tree(tree2007.lc11, detail=TRUE))
sink()
# 2008
sink("output-2008-tree-overfit-summary-lc1.txt", append=FALSE, split=TRUE)
print(tree2008.lc1)
print(summary(tree2008.lc1))
print(misclass.tree(tree2008.lc1, detail=TRUE))
sink()
sink("output-2008-tree-overfit-summary-lc2.txt", append=FALSE, split=TRUE)
print(tree2008.lc2)
print(summary(tree2008.lc2))
print(misclass.tree(tree2008.lc2, detail=TRUE))
sink()
sink("output-2008-tree-overfit-summary-lc3.txt", append=FALSE, split=TRUE)
print(tree2008.lc3)
print(summary(tree2008.lc3))
print(misclass.tree(tree2008.lc3, detail=TRUE))
sink()
sink("output-2008-tree-overfit-summary-lc4.txt", append=FALSE, split=TRUE)
print(tree2008.lc4)
print(summary(tree2008.lc4))
print(misclass.tree(tree2008.lc4, detail=TRUE))
sink()
sink("output-2008-tree-overfit-summary-lc5.txt", append=FALSE, split=TRUE)
print(tree2008.lc5)
print(summary(tree2008.lc5))
print(misclass.tree(tree2008.lc5, detail=TRUE))
sink()
sink("output-2008-tree-overfit-summary-lc6.txt", append=FALSE, split=TRUE)
print(tree2008.lc6)
print(summary(tree2008.lc6))
print(misclass.tree(tree2008.lc6, detail=TRUE))
sink()
sink("output-2008-tree-overfit-summary-lc7.txt", append=FALSE, split=TRUE)
print(tree2008.lc7)
print(summary(tree2008.lc7))
print(misclass.tree(tree2008.lc7, detail=TRUE))
sink()
sink("output-2008-tree-overfit-summary-lc8.txt", append=FALSE, split=TRUE)
print(tree2008.lc8)
print(summary(tree2008.lc8))
print(misclass.tree(tree2008.lc8, detail=TRUE))
sink()
sink("output-2008-tree-overfit-summary-lc9.txt", append=FALSE, split=TRUE)
print(tree2008.lc9)
print(summary(tree2008.lc9))
print(misclass.tree(tree2008.lc9, detail=TRUE))
sink()
sink("output-2008-tree-overfit-summary-lc10.txt", append=FALSE, split=TRUE)
print(tree2008.lc10)
print(summary(tree2008.lc10))
print(misclass.tree(tree2008.lc10, detail=TRUE))
sink()
sink("output-2008-tree-overfit-summary-lc11.txt", append=FALSE, split=TRUE)
print(tree2008.lc11)
print(summary(tree2008.lc11))
print(misclass.tree(tree2008.lc11, detail=TRUE))
sink()
# 2009
sink("output-2009-tree-overfit-summary-lc1.txt", append=FALSE, split=TRUE)
print(tree2009.lc1)
print(summary(tree2009.lc1))
print(misclass.tree(tree2009.lc1, detail=TRUE))
sink()
sink("output-2009-tree-overfit-summary-lc2.txt", append=FALSE, split=TRUE)
print(tree2009.lc2)
print(summary(tree2009.lc2))
print(misclass.tree(tree2009.lc2, detail=TRUE))
sink()
sink("output-2009-tree-overfit-summary-lc3.txt", append=FALSE, split=TRUE)
print(tree2009.lc3)
print(summary(tree2009.lc3))
print(misclass.tree(tree2009.lc3, detail=TRUE))
sink()
sink("output-2009-tree-overfit-summary-lc4.txt", append=FALSE, split=TRUE)
print(tree2009.lc4)
print(summary(tree2009.lc4))
print(misclass.tree(tree2009.lc4, detail=TRUE))
sink()
sink("output-2009-tree-overfit-summary-lc5.txt", append=FALSE, split=TRUE)
print(tree2009.lc5)
print(summary(tree2009.lc5))
print(misclass.tree(tree2009.lc5, detail=TRUE))
sink()
sink("output-2009-tree-overfit-summary-lc6.txt", append=FALSE, split=TRUE)
print(tree2009.lc6)
print(summary(tree2009.lc6))
print(misclass.tree(tree2009.lc6, detail=TRUE))
sink()
sink("output-2009-tree-overfit-summary-lc7.txt", append=FALSE, split=TRUE)
print(tree2009.lc7)
print(summary(tree2009.lc7))
print(misclass.tree(tree2009.lc7, detail=TRUE))
sink()
sink("output-2009-tree-overfit-summary-lc8.txt", append=FALSE, split=TRUE)
print(tree2009.lc8)
print(summary(tree2009.lc8))
print(misclass.tree(tree2009.lc8, detail=TRUE))
sink()
sink("output-2009-tree-overfit-summary-lc9.txt", append=FALSE, split=TRUE)
print(tree2009.lc9)
print(summary(tree2009.lc9))
print(misclass.tree(tree2009.lc9, detail=TRUE))
sink()
sink("output-2009-tree-overfit-summary-lc10.txt", append=FALSE, split=TRUE)
print(tree2009.lc10)
print(summary(tree2009.lc10))
print(misclass.tree(tree2009.lc10, detail=TRUE))
sink()
sink("output-2009-tree-overfit-summary-lc11.txt", append=FALSE, split=TRUE)
print(tree2009.lc11)
print(summary(tree2009.lc11))
print(misclass.tree(tree2009.lc11, detail=TRUE))
sink()
# 2010
sink("output-2010-tree-overfit-summary-lc1.txt", append=FALSE, split=TRUE)
print(tree2010.lc1)
print(summary(tree2010.lc1))
print(misclass.tree(tree2010.lc1, detail=TRUE))
sink()
sink("output-2010-tree-overfit-summary-lc2.txt", append=FALSE, split=TRUE)
print(tree2010.lc2)
print(summary(tree2010.lc2))
print(misclass.tree(tree2010.lc2, detail=TRUE))
sink()
sink("output-2010-tree-overfit-summary-lc3.txt", append=FALSE, split=TRUE)
print(tree2010.lc3)
print(summary(tree2010.lc3))
print(misclass.tree(tree2010.lc3, detail=TRUE))
sink()
sink("output-2010-tree-overfit-summary-lc4.txt", append=FALSE, split=TRUE)
print(tree2010.lc4)
print(summary(tree2010.lc4))
print(misclass.tree(tree2010.lc4, detail=TRUE))
sink()
sink("output-2010-tree-overfit-summary-lc5.txt", append=FALSE, split=TRUE)
print(tree2010.lc5)
print(summary(tree2010.lc5))
print(misclass.tree(tree2010.lc5, detail=TRUE))
sink()
sink("output-2010-tree-overfit-summary-lc6.txt", append=FALSE, split=TRUE)
print(tree2010.lc6)
print(summary(tree2010.lc6))
print(misclass.tree(tree2010.lc6, detail=TRUE))
sink()
sink("output-2010-tree-overfit-summary-lc7.txt", append=FALSE, split=TRUE)
print(tree2010.lc7)
print(summary(tree2010.lc7))
print(misclass.tree(tree2010.lc7, detail=TRUE))
sink()
sink("output-2010-tree-overfit-summary-lc8.txt", append=FALSE, split=TRUE)
print(tree2010.lc8)
print(summary(tree2010.lc8))
print(misclass.tree(tree2010.lc8, detail=TRUE))
sink()
sink("output-2010-tree-overfit-summary-lc9.txt", append=FALSE, split=TRUE)
print(tree2010.lc9)
print(summary(tree2010.lc9))
print(misclass.tree(tree2010.lc9, detail=TRUE))
sink()
sink("output-2010-tree-overfit-summary-lc10.txt", append=FALSE, split=TRUE)
print(tree2010.lc10)
print(summary(tree2010.lc10))
print(misclass.tree(tree2010.lc10, detail=TRUE))
sink()
sink("output-2010-tree-overfit-summary-lc11.txt", append=FALSE, split=TRUE)
print(tree2010.lc11)
print(summary(tree2010.lc11))
print(misclass.tree(tree2010.lc11, detail=TRUE))
sink()

# Generate tree summary and misclassification statistics (pruned) and save as TXT file

# 2007
sink("output-2007-tree-pruned-summary-lc1.txt", append=FALSE, split=TRUE)
print(prune2007.lc1)
print(summary(prune2007.lc1))
print(misclass.tree(prune2007.lc1, detail=TRUE))
sink()
sink("output-2007-tree-pruned-summary-lc2.txt", append=FALSE, split=TRUE)
print(prune2007.lc2)
print(summary(prune2007.lc2))
print(misclass.tree(prune2007.lc2, detail=TRUE))
sink()
sink("output-2007-tree-pruned-summary-lc3.txt", append=FALSE, split=TRUE)
print(prune2007.lc3)
print(summary(prune2007.lc3))
print(misclass.tree(prune2007.lc3, detail=TRUE))
sink()
sink("output-2007-tree-pruned-summary-lc4.txt", append=FALSE, split=TRUE)
print(prune2007.lc4)
print(summary(prune2007.lc4))
print(misclass.tree(prune2007.lc4, detail=TRUE))
sink()
sink("output-2007-tree-pruned-summary-lc5.txt", append=FALSE, split=TRUE)
print(prune2007.lc5)
print(summary(prune2007.lc5))
print(misclass.tree(prune2007.lc5, detail=TRUE))
sink()
sink("output-2007-tree-pruned-summary-lc6.txt", append=FALSE, split=TRUE)
print(prune2007.lc6)
print(summary(prune2007.lc6))
print(misclass.tree(prune2007.lc6, detail=TRUE))
sink()
sink("output-2007-tree-pruned-summary-lc7.txt", append=FALSE, split=TRUE)
print(prune2007.lc7)
print(summary(prune2007.lc7))
print(misclass.tree(prune2007.lc7, detail=TRUE))
sink()
sink("output-2007-tree-pruned-summary-lc8.txt", append=FALSE, split=TRUE)
print(prune2007.lc8)
print(summary(prune2007.lc8))
print(misclass.tree(prune2007.lc8, detail=TRUE))
sink()
sink("output-2007-tree-pruned-summary-lc9.txt", append=FALSE, split=TRUE)
print(prune2007.lc9)
print(summary(prune2007.lc9))
print(misclass.tree(prune2007.lc9, detail=TRUE))
sink()
sink("output-2007-tree-pruned-summary-lc10.txt", append=FALSE, split=TRUE)
print(prune2007.lc10)
print(summary(prune2007.lc10))
print(misclass.tree(prune2007.lc10, detail=TRUE))
sink()
sink("output-2007-tree-pruned-summary-lc11.txt", append=FALSE, split=TRUE)
print(prune2007.lc11)
print(summary(prune2007.lc11))
print(misclass.tree(prune2007.lc11, detail=TRUE))
sink()
# 2008
sink("output-2008-tree-pruned-summary-lc1.txt", append=FALSE, split=TRUE)
print(prune2008.lc1)
print(summary(prune2008.lc1))
print(misclass.tree(prune2008.lc1, detail=TRUE))
sink()
sink("output-2008-tree-pruned-summary-lc2.txt", append=FALSE, split=TRUE)
print(prune2008.lc2)
print(summary(prune2008.lc2))
print(misclass.tree(prune2008.lc2, detail=TRUE))
sink()
sink("output-2008-tree-pruned-summary-lc3.txt", append=FALSE, split=TRUE)
print(prune2008.lc3)
print(summary(prune2008.lc3))
print(misclass.tree(prune2008.lc3, detail=TRUE))
sink()
sink("output-2008-tree-pruned-summary-lc4.txt", append=FALSE, split=TRUE)
print(prune2008.lc4)
print(summary(prune2008.lc4))
print(misclass.tree(prune2008.lc4, detail=TRUE))
sink()
sink("output-2008-tree-pruned-summary-lc5.txt", append=FALSE, split=TRUE)
print(prune2008.lc5)
print(summary(prune2008.lc5))
print(misclass.tree(prune2008.lc5, detail=TRUE))
sink()
sink("output-2008-tree-pruned-summary-lc6.txt", append=FALSE, split=TRUE)
print(prune2008.lc6)
print(summary(prune2008.lc6))
print(misclass.tree(prune2008.lc6, detail=TRUE))
sink()
sink("output-2008-tree-pruned-summary-lc7.txt", append=FALSE, split=TRUE)
print(prune2008.lc7)
print(summary(prune2008.lc7))
print(misclass.tree(prune2008.lc7, detail=TRUE))
sink()
sink("output-2008-tree-pruned-summary-lc8.txt", append=FALSE, split=TRUE)
print(prune2008.lc8)
print(summary(prune2008.lc8))
print(misclass.tree(prune2008.lc8, detail=TRUE))
sink()
sink("output-2008-tree-pruned-summary-lc9.txt", append=FALSE, split=TRUE)
print(prune2008.lc9)
print(summary(prune2008.lc9))
print(misclass.tree(prune2008.lc9, detail=TRUE))
sink()
sink("output-2008-tree-pruned-summary-lc10.txt", append=FALSE, split=TRUE)
print(prune2008.lc10)
print(summary(prune2008.lc10))
print(misclass.tree(prune2008.lc10, detail=TRUE))
sink()
sink("output-2008-tree-pruned-summary-lc11.txt", append=FALSE, split=TRUE)
print(prune2008.lc11)
print(summary(prune2008.lc11))
print(misclass.tree(prune2008.lc11, detail=TRUE))
sink()
# 2009
sink("output-2009-tree-pruned-summary-lc1.txt", append=FALSE, split=TRUE)
print(prune2009.lc1)
print(summary(prune2009.lc1))
print(misclass.tree(prune2009.lc1, detail=TRUE))
sink()
sink("output-2009-tree-pruned-summary-lc2.txt", append=FALSE, split=TRUE)
print(prune2009.lc2)
print(summary(prune2009.lc2))
print(misclass.tree(prune2009.lc2, detail=TRUE))
sink()
sink("output-2009-tree-pruned-summary-lc3.txt", append=FALSE, split=TRUE)
print(prune2009.lc3)
print(summary(prune2009.lc3))
print(misclass.tree(prune2009.lc3, detail=TRUE))
sink()
sink("output-2009-tree-pruned-summary-lc4.txt", append=FALSE, split=TRUE)
print(prune2009.lc4)
print(summary(prune2009.lc4))
print(misclass.tree(prune2009.lc4, detail=TRUE))
sink()
sink("output-2009-tree-pruned-summary-lc5.txt", append=FALSE, split=TRUE)
print(prune2009.lc5)
print(summary(prune2009.lc5))
print(misclass.tree(prune2009.lc5, detail=TRUE))
sink()
sink("output-2009-tree-pruned-summary-lc6.txt", append=FALSE, split=TRUE)
print(prune2009.lc6)
print(summary(prune2009.lc6))
print(misclass.tree(prune2009.lc6, detail=TRUE))
sink()
sink("output-2009-tree-pruned-summary-lc7.txt", append=FALSE, split=TRUE)
print(prune2009.lc7)
print(summary(prune2009.lc7))
print(misclass.tree(prune2009.lc7, detail=TRUE))
sink()
sink("output-2009-tree-pruned-summary-lc8.txt", append=FALSE, split=TRUE)
print(prune2009.lc8)
print(summary(prune2009.lc8))
print(misclass.tree(prune2009.lc8, detail=TRUE))
sink()
sink("output-2009-tree-pruned-summary-lc9.txt", append=FALSE, split=TRUE)
print(prune2009.lc9)
print(summary(prune2009.lc9))
print(misclass.tree(prune2009.lc9, detail=TRUE))
sink()
sink("output-2009-tree-pruned-summary-lc10.txt", append=FALSE, split=TRUE)
print(prune2009.lc10)
print(summary(prune2009.lc10))
print(misclass.tree(prune2009.lc10, detail=TRUE))
sink()
sink("output-2009-tree-pruned-summary-lc11.txt", append=FALSE, split=TRUE)
print(prune2009.lc11)
print(summary(prune2009.lc11))
print(misclass.tree(prune2009.lc11, detail=TRUE))
sink()
# 2010
sink("output-2010-tree-pruned-summary-lc1.txt", append=FALSE, split=TRUE)
print(prune2010.lc1)
print(summary(prune2010.lc1))
print(misclass.tree(prune2010.lc1, detail=TRUE))
sink()
sink("output-2010-tree-pruned-summary-lc2.txt", append=FALSE, split=TRUE)
print(prune2010.lc2)
print(summary(prune2010.lc2))
print(misclass.tree(prune2010.lc2, detail=TRUE))
sink()
sink("output-2010-tree-pruned-summary-lc3.txt", append=FALSE, split=TRUE)
print(prune2010.lc3)
print(summary(prune2010.lc3))
print(misclass.tree(prune2010.lc3, detail=TRUE))
sink()
sink("output-2010-tree-pruned-summary-lc4.txt", append=FALSE, split=TRUE)
print(prune2010.lc4)
print(summary(prune2010.lc4))
print(misclass.tree(prune2010.lc4, detail=TRUE))
sink()
sink("output-2010-tree-pruned-summary-lc5.txt", append=FALSE, split=TRUE)
print(prune2010.lc5)
print(summary(prune2010.lc5))
print(misclass.tree(prune2010.lc5, detail=TRUE))
sink()
sink("output-2010-tree-pruned-summary-lc6.txt", append=FALSE, split=TRUE)
print(prune2010.lc6)
print(summary(prune2010.lc6))
print(misclass.tree(prune2010.lc6, detail=TRUE))
sink()
sink("output-2010-tree-pruned-summary-lc7.txt", append=FALSE, split=TRUE)
print(prune2010.lc7)
print(summary(prune2010.lc7))
print(misclass.tree(prune2010.lc7, detail=TRUE))
sink()
sink("output-2010-tree-pruned-summary-lc8.txt", append=FALSE, split=TRUE)
print(prune2010.lc8)
print(summary(prune2010.lc8))
print(misclass.tree(prune2010.lc8, detail=TRUE))
sink()
sink("output-2010-tree-pruned-summary-lc9.txt", append=FALSE, split=TRUE)
print(prune2010.lc9)
print(summary(prune2010.lc9))
print(misclass.tree(prune2010.lc9, detail=TRUE))
sink()
sink("output-2010-tree-pruned-summary-lc10.txt", append=FALSE, split=TRUE)
print(prune2010.lc10)
print(summary(prune2010.lc10))
print(misclass.tree(prune2010.lc10, detail=TRUE))
sink()
sink("output-2010-tree-pruned-summary-lc11.txt", append=FALSE, split=TRUE)
print(prune2010.lc11)
print(summary(prune2010.lc11))
print(misclass.tree(prune2010.lc11, detail=TRUE))
sink()

# Plot tree object/dendrogram (overfitted) and save as PDF file

# 2007
pdf("output-2007-overfit-dendrogram-lc1.pdf", width=7, height=5.5)
plot(tree2007.lc1)
text(tree2007.lc1, cex=0.70)
dev.off()
pdf("output-2007-overfit-dendrogram-lc2.pdf", width=7, height=5.5)
plot(tree2007.lc2)
text(tree2007.lc2, cex=0.70)
dev.off()
pdf("output-2007-overfit-dendrogram-lc3.pdf", width=7, height=5.5)
plot(tree2007.lc3)
text(tree2007.lc3, cex=0.70)
dev.off()
pdf("output-2007-overfit-dendrogram-lc4.pdf", width=7, height=5.5)
plot(tree2007.lc4)
text(tree2007.lc4, cex=0.70)
dev.off()
pdf("output-2007-overfit-dendrogram-lc5.pdf", width=7, height=5.5)
plot(tree2007.lc5)
text(tree2007.lc5, cex=0.70)
dev.off()
pdf("output-2007-overfit-dendrogram-lc6.pdf", width=7, height=5.5)
plot(tree2007.lc6)
text(tree2007.lc6, cex=0.70)
dev.off()
pdf("output-2007-overfit-dendrogram-lc7.pdf", width=7, height=5.5)
plot(tree2007.lc7)
text(tree2007.lc7, cex=0.70)
dev.off()
pdf("output-2007-overfit-dendrogram-lc8.pdf", width=7, height=5.5)
plot(tree2007.lc8)
text(tree2007.lc8, cex=0.70)
dev.off()
pdf("output-2007-overfit-dendrogram-lc9.pdf", width=7, height=5.5)
plot(tree2007.lc9)
text(tree2007.lc9, cex=0.70)
dev.off()
pdf("output-2007-overfit-dendrogram-lc10.pdf", width=7, height=5.5)
plot(tree2007.lc10)
text(tree2007.lc10, cex=0.70)
dev.off()
pdf("output-2007-overfit-dendrogram-lc11.pdf", width=7, height=5.5)
plot(tree2007.lc11)
text(tree2007.lc11, cex=0.70)
dev.off()
# 2008
pdf("output-2008-overfit-dendrogram-lc1.pdf", width=7, height=5.5)
plot(tree2008.lc1)
text(tree2008.lc1, cex=0.70)
dev.off()
pdf("output-2008-overfit-dendrogram-lc2.pdf", width=7, height=5.5)
plot(tree2008.lc2)
text(tree2008.lc2, cex=0.70)
dev.off()
pdf("output-2008-overfit-dendrogram-lc3.pdf", width=7, height=5.5)
plot(tree2008.lc3)
text(tree2008.lc3, cex=0.70)
dev.off()
pdf("output-2008-overfit-dendrogram-lc4.pdf", width=7, height=5.5)
plot(tree2008.lc4)
text(tree2008.lc4, cex=0.70)
dev.off()
pdf("output-2008-overfit-dendrogram-lc5.pdf", width=7, height=5.5)
plot(tree2008.lc5)
text(tree2008.lc5, cex=0.70)
dev.off()
pdf("output-2008-overfit-dendrogram-lc6.pdf", width=7, height=5.5)
plot(tree2008.lc6)
text(tree2008.lc6, cex=0.70)
dev.off()
pdf("output-2008-overfit-dendrogram-lc7.pdf", width=7, height=5.5)
plot(tree2008.lc7)
text(tree2008.lc7, cex=0.70)
dev.off()
pdf("output-2008-overfit-dendrogram-lc8.pdf", width=7, height=5.5)
plot(tree2008.lc8)
text(tree2008.lc8, cex=0.70)
dev.off()
pdf("output-2008-overfit-dendrogram-lc9.pdf", width=7, height=5.5)
plot(tree2008.lc9)
text(tree2008.lc9, cex=0.70)
dev.off()
pdf("output-2008-overfit-dendrogram-lc10.pdf", width=7, height=5.5)
plot(tree2008.lc10)
text(tree2008.lc10, cex=0.70)
dev.off()
pdf("output-2008-overfit-dendrogram-lc11.pdf", width=7, height=5.5)
plot(tree2008.lc11)
text(tree2008.lc11, cex=0.70)
dev.off()
# 2009
pdf("output-2009-overfit-dendrogram-lc1.pdf", width=7, height=5.5)
plot(tree2009.lc1)
text(tree2009.lc1, cex=0.70)
dev.off()
pdf("output-2009-overfit-dendrogram-lc2.pdf", width=7, height=5.5)
plot(tree2009.lc2)
text(tree2009.lc2, cex=0.70)
dev.off()
pdf("output-2009-overfit-dendrogram-lc3.pdf", width=7, height=5.5)
plot(tree2009.lc3)
text(tree2009.lc3, cex=0.70)
dev.off()
pdf("output-2009-overfit-dendrogram-lc4.pdf", width=7, height=5.5)
plot(tree2009.lc4)
text(tree2009.lc4, cex=0.70)
dev.off()
pdf("output-2009-overfit-dendrogram-lc5.pdf", width=7, height=5.5)
plot(tree2009.lc5)
text(tree2009.lc5, cex=0.70)
dev.off()
pdf("output-2009-overfit-dendrogram-lc6.pdf", width=7, height=5.5)
plot(tree2009.lc6)
text(tree2009.lc6, cex=0.70)
dev.off()
pdf("output-2009-overfit-dendrogram-lc7.pdf", width=7, height=5.5)
plot(tree2009.lc7)
text(tree2009.lc7, cex=0.70)
dev.off()
pdf("output-2009-overfit-dendrogram-lc8.pdf", width=7, height=5.5)
plot(tree2009.lc8)
text(tree2009.lc8, cex=0.70)
dev.off()
pdf("output-2009-overfit-dendrogram-lc9.pdf", width=7, height=5.5)
plot(tree2009.lc9)
text(tree2009.lc9, cex=0.70)
dev.off()
pdf("output-2009-overfit-dendrogram-lc10.pdf", width=7, height=5.5)
plot(tree2009.lc10)
text(tree2009.lc10, cex=0.70)
dev.off()
pdf("output-2009-overfit-dendrogram-lc11.pdf", width=7, height=5.5)
plot(tree2009.lc11)
text(tree2009.lc11, cex=0.70)
dev.off()
# 2010
pdf("output-2010-overfit-dendrogram-lc1.pdf", width=7, height=5.5)
plot(tree2010.lc1)
text(tree2010.lc1, cex=0.70)
dev.off()
pdf("output-2010-overfit-dendrogram-lc2.pdf", width=7, height=5.5)
plot(tree2010.lc2)
text(tree2010.lc2, cex=0.70)
dev.off()
pdf("output-2010-overfit-dendrogram-lc3.pdf", width=7, height=5.5)
plot(tree2010.lc3)
text(tree2010.lc3, cex=0.70)
dev.off()
pdf("output-2010-overfit-dendrogram-lc4.pdf", width=7, height=5.5)
plot(tree2010.lc4)
text(tree2010.lc4, cex=0.70)
dev.off()
pdf("output-2010-overfit-dendrogram-lc5.pdf", width=7, height=5.5)
plot(tree2010.lc5)
text(tree2010.lc5, cex=0.70)
dev.off()
pdf("output-2010-overfit-dendrogram-lc6.pdf", width=7, height=5.5)
plot(tree2010.lc6)
text(tree2010.lc6, cex=0.70)
dev.off()
pdf("output-2010-overfit-dendrogram-lc7.pdf", width=7, height=5.5)
plot(tree2010.lc7)
text(tree2010.lc7, cex=0.70)
dev.off()
pdf("output-2010-overfit-dendrogram-lc8.pdf", width=7, height=5.5)
plot(tree2010.lc8)
text(tree2010.lc8, cex=0.70)
dev.off()
pdf("output-2010-overfit-dendrogram-lc9.pdf", width=7, height=5.5)
plot(tree2010.lc9)
text(tree2010.lc9, cex=0.70)
dev.off()
pdf("output-2010-overfit-dendrogram-lc10.pdf", width=7, height=5.5)
plot(tree2010.lc10)
text(tree2010.lc10, cex=0.70)
dev.off()
pdf("output-2010-overfit-dendrogram-lc11.pdf", width=7, height=5.5)
plot(tree2010.lc11)
text(tree2010.lc11, cex=0.70)
dev.off()

# Plot tree object (pruned) and save as PDF file

# 2007
pdf("output-2007-pruned-dendrogram-lc1.pdf", width=7, height=5.5)
plot(prune2007.lc1)
text(prune2007.lc1, cex=0.70)
dev.off()
pdf("output-2007-pruned-dendrogram-lc2.pdf", width=7, height=5.5)
plot(prune2007.lc2)
text(prune2007.lc2, cex=0.70)
dev.off()
pdf("output-2007-pruned-dendrogram-lc3.pdf", width=7, height=5.5)
plot(prune2007.lc3)
text(prune2007.lc3, cex=0.70)
dev.off()
pdf("output-2007-pruned-dendrogram-lc4.pdf", width=7, height=5.5)
plot(prune2007.lc4)
text(prune2007.lc4, cex=0.70)
dev.off()
pdf("output-2007-pruned-dendrogram-lc5.pdf", width=7, height=5.5)
plot(prune2007.lc5)
text(prune2007.lc5, cex=0.70)
dev.off()
pdf("output-2007-pruned-dendrogram-lc6.pdf", width=7, height=5.5)
plot(prune2007.lc6)
text(prune2007.lc6, cex=0.70)
dev.off()
pdf("output-2007-pruned-dendrogram-lc7.pdf", width=7, height=5.5)
plot(prune2007.lc7)
text(prune2007.lc7, cex=0.70)
dev.off()
pdf("output-2007-pruned-dendrogram-lc8.pdf", width=7, height=5.5)
plot(prune2007.lc8)
text(prune2007.lc8, cex=0.70)
dev.off()
pdf("output-2007-pruned-dendrogram-lc9.pdf", width=7, height=5.5)
plot(prune2007.lc9)
text(prune2007.lc9, cex=0.70)
dev.off()
pdf("output-2007-pruned-dendrogram-lc10.pdf", width=7, height=5.5)
plot(prune2007.lc10)
text(prune2007.lc10, cex=0.70)
dev.off()
pdf("output-2007-pruned-dendrogram-lc11.pdf", width=7, height=5.5)
plot(prune2007.lc11)
text(prune2007.lc11, cex=0.70)
dev.off()
# 2008
pdf("output-2008-pruned-dendrogram-lc1.pdf", width=7, height=5.5)
plot(prune2008.lc1)
text(prune2008.lc1, cex=0.70)
dev.off()
pdf("output-2008-pruned-dendrogram-lc2.pdf", width=7, height=5.5)
plot(prune2008.lc2)
text(prune2008.lc2, cex=0.70)
dev.off()
pdf("output-2008-pruned-dendrogram-lc3.pdf", width=7, height=5.5)
plot(prune2008.lc3)
text(prune2008.lc3, cex=0.70)
dev.off()
pdf("output-2008-pruned-dendrogram-lc4.pdf", width=7, height=5.5)
plot(prune2008.lc4)
text(prune2008.lc4, cex=0.70)
dev.off()
pdf("output-2008-pruned-dendrogram-lc5.pdf", width=7, height=5.5)
plot(prune2008.lc5)
text(prune2008.lc5, cex=0.70)
dev.off()
pdf("output-2008-pruned-dendrogram-lc6.pdf", width=7, height=5.5)
plot(prune2008.lc6)
text(prune2008.lc6, cex=0.70)
dev.off()
pdf("output-2008-pruned-dendrogram-lc7.pdf", width=7, height=5.5)
plot(prune2008.lc7)
text(prune2008.lc7, cex=0.70)
dev.off()
pdf("output-2008-pruned-dendrogram-lc8.pdf", width=7, height=5.5)
plot(prune2008.lc8)
text(prune2008.lc8, cex=0.70)
dev.off()
pdf("output-2008-pruned-dendrogram-lc9.pdf", width=7, height=5.5)
plot(prune2008.lc9)
text(prune2008.lc9, cex=0.70)
dev.off()
pdf("output-2008-pruned-dendrogram-lc10.pdf", width=7, height=5.5)
plot(prune2008.lc10)
text(prune2008.lc10, cex=0.70)
dev.off()
pdf("output-2008-pruned-dendrogram-lc11.pdf", width=7, height=5.5)
plot(prune2008.lc11)
text(prune2008.lc11, cex=0.70)
dev.off()
# 2009
pdf("output-2009-pruned-dendrogram-lc1.pdf", width=7, height=5.5)
plot(prune2009.lc1)
text(prune2009.lc1, cex=0.70)
dev.off()
pdf("output-2009-pruned-dendrogram-lc2.pdf", width=7, height=5.5)
plot(prune2009.lc2)
text(prune2009.lc2, cex=0.70)
dev.off()
pdf("output-2009-pruned-dendrogram-lc3.pdf", width=7, height=5.5)
plot(prune2009.lc3)
text(prune2009.lc3, cex=0.70)
dev.off()
pdf("output-2009-pruned-dendrogram-lc4.pdf", width=7, height=5.5)
plot(prune2009.lc4)
text(prune2009.lc4, cex=0.70)
dev.off()
pdf("output-2009-pruned-dendrogram-lc5.pdf", width=7, height=5.5)
plot(prune2009.lc5)
text(prune2009.lc5, cex=0.70)
dev.off()
pdf("output-2009-pruned-dendrogram-lc6.pdf", width=7, height=5.5)
plot(prune2009.lc6)
text(prune2009.lc6, cex=0.70)
dev.off()
pdf("output-2009-pruned-dendrogram-lc7.pdf", width=7, height=5.5)
plot(prune2009.lc7)
text(prune2009.lc7, cex=0.70)
dev.off()
pdf("output-2009-pruned-dendrogram-lc8.pdf", width=7, height=5.5)
plot(prune2009.lc8)
text(prune2009.lc8, cex=0.70)
dev.off()
pdf("output-2009-pruned-dendrogram-lc9.pdf", width=7, height=5.5)
plot(prune2009.lc9)
text(prune2009.lc9, cex=0.70)
dev.off()
pdf("output-2009-pruned-dendrogram-lc10.pdf", width=7, height=5.5)
plot(prune2009.lc10)
text(prune2009.lc10, cex=0.70)
dev.off()
pdf("output-2009-pruned-dendrogram-lc11.pdf", width=7, height=5.5)
plot(prune2009.lc11)
text(prune2009.lc11, cex=0.70)
dev.off()
# 2010
pdf("output-2010-pruned-dendrogram-lc1.pdf", width=7, height=5.5)
plot(prune2010.lc1)
text(prune2010.lc1, cex=0.70)
dev.off()
pdf("output-2010-pruned-dendrogram-lc2.pdf", width=7, height=5.5)
plot(prune2010.lc2)
text(prune2010.lc2, cex=0.70)
dev.off()
pdf("output-2010-pruned-dendrogram-lc3.pdf", width=7, height=5.5)
plot(prune2010.lc3)
text(prune2010.lc3, cex=0.70)
dev.off()
pdf("output-2010-pruned-dendrogram-lc4.pdf", width=7, height=5.5)
plot(prune2010.lc4)
text(prune2010.lc4, cex=0.70)
dev.off()
pdf("output-2010-pruned-dendrogram-lc5.pdf", width=7, height=5.5)
plot(prune2010.lc5)
text(prune2010.lc5, cex=0.70)
dev.off()
pdf("output-2010-pruned-dendrogram-lc6.pdf", width=7, height=5.5)
plot(prune2010.lc6)
text(prune2010.lc6, cex=0.70)
dev.off()
pdf("output-2010-pruned-dendrogram-lc7.pdf", width=7, height=5.5)
plot(prune2010.lc7)
text(prune2010.lc7, cex=0.70)
dev.off()
pdf("output-2010-pruned-dendrogram-lc8.pdf", width=7, height=5.5)
plot(prune2010.lc8)
text(prune2010.lc8, cex=0.70)
dev.off()
pdf("output-2010-pruned-dendrogram-lc9.pdf", width=7, height=5.5)
plot(prune2010.lc9)
text(prune2010.lc9, cex=0.70)
dev.off()
pdf("output-2010-pruned-dendrogram-lc10.pdf", width=7, height=5.5)
plot(prune2010.lc10)
text(prune2010.lc10, cex=0.70)
dev.off()
pdf("output-2010-pruned-dendrogram-lc11.pdf", width=7, height=5.5)
plot(prune2010.lc11)
text(prune2010.lc11, cex=0.70)
dev.off()
