# This R script implements hierarchical clustering using pvclust package and compare
# dendrograms using dendextend package. The aim of the clustering is to find natural 
# clusters of forest types based on predictor variables or features derived from 
# 5x5 square image object statistics generated by eCognition. The purpose of comparing
# dendrograms is to assess consistencies in clustering across years and variables by 
# evaluating similarities of dendrograms based on available metrics.
#
# Script By:      Jose Don T. De Alban
# Date Created:   22 Jan 2016
# Last Modified:  03 Mar 2016 

# Load the required R libraries
library(pvclust)
library(dendextend)
library(magrittr)
library(corrplot)
library(ggplot2)

# CASE 1: POLARISATION

# Set working directory
setwd("/Users/dondealban/Image Processing/Thesis/R/3 clustering 2016/")

# Read data, define variables, and store data in variables
raw2007 <- as.matrix(read.csv(file="PALSARwDEM-NLuzon-Clustering-2007-CBS.csv", header=TRUE, sep=",", row.name = 1))
raw2008 <- as.matrix(read.csv(file="PALSARwDEM-NLuzon-Clustering-2008-CBS.csv", header=TRUE, sep=",", row.name = 1))
raw2009 <- as.matrix(read.csv(file="PALSARwDEM-NLuzon-Clustering-2009-CBS.csv", header=TRUE, sep=",", row.name = 1))
raw2010 <- as.matrix(read.csv(file="PALSARwDEM-NLuzon-Clustering-2010-CBS.csv", header=TRUE, sep=",", row.name = 1))

# Normalise variables by rescaling for compatibility of resulting clusters
nlz2007 <- scale(raw2007)
nlz2008 <- scale(raw2008)
nlz2009 <- scale(raw2009)
nlz2010 <- scale(raw2010)

# Subset data by selecting variables
nlz2007c1 <- nlz2007[,c(40:42,48:50)]
nlz2008c1 <- nlz2008[,c(40:42,48:50)]
nlz2009c1 <- nlz2009[,c(40:42,48:50)]
nlz2010c1 <- nlz2010[,c(40:42,48:50)]

# Transpose matrix elements
tnlz2007c1 = t(nlz2007c1)
tnlz2008c1 = t(nlz2008c1)
tnlz2009c1 = t(nlz2009c1)
tnlz2010c1 = t(nlz2010c1)

# Hierarchical clustering using pvclust package
clust.nlz2007c1 <- pvclust(tnlz2007c1, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2008c1 <- pvclust(tnlz2008c1, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2009c1 <- pvclust(tnlz2009c1, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2010c1 <- pvclust(tnlz2010c1, method.hclust="average", method.dist="euclidean", nboot=1000)

# Plot dendrograms and save as PDF file
pdf("output-dendrogram-2007-case1.pdf", width=7, height=5.5)
clust.nlz2007c1 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2007 Case 1")
clust.nlz2007c1 %>% text
clust.nlz2007c1 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2008-case1.pdf", width=7, height=5.5)
clust.nlz2008c1 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2008 Case 1")
clust.nlz2008c1 %>% text
clust.nlz2008c1 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2009-case1.pdf", width=7, height=5.5)
clust.nlz2009c1 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2009 Case 1")
clust.nlz2009c1 %>% text
clust.nlz2009c1 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2010-case1.pdf", width=7, height=5.5)
clust.nlz2010c1 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2010 Case 1")
clust.nlz2010c1 %>% text
clust.nlz2010c1 %>% pvrect(alpha=0.95)
dev.off()

# Convert pvclust object variables to dendextend object variables
dend2007c1 <- as.dendrogram(clust.nlz2007c1)
dend2008c1 <- as.dendrogram(clust.nlz2008c1)
dend2009c1 <- as.dendrogram(clust.nlz2009c1)
dend2010c1 <- as.dendrogram(clust.nlz2010c1)

# Create a dendlist object from several dendrograms
list.dend78910c1 <- dendlist(dend2007c1, dend2008c1, dend2009c1, dend2010c1)

# Perform global comparison of two or more dendrograms to test if they are equal
equal.dend78910c1 <- all.equal(list.dend78910c1)

# Generate correlation matrix between a list of trees
cormat.dend78910c1 <- cor.dendlist(list.dend78910c1)

# Compute Baker's Gamma Index
bg0708c1 <- cor_bakers_gamma(dend2007c1, dend2008c1)
bg0709c1 <- cor_bakers_gamma(dend2007c1, dend2009c1)
bg0710c1 <- cor_bakers_gamma(dend2007c1, dend2010c1)
bg0809c1 <- cor_bakers_gamma(dend2008c1, dend2009c1)
bg0810c1 <- cor_bakers_gamma(dend2008c1, dend2010c1)
bg0910c1 <- cor_bakers_gamma(dend2009c1, dend2010c1)

# Compute Cophenetic Correlation coefficient
cr0708c1 <- cor_cophenetic(dend2007c1, dend2008c1)
cr0709c1 <- cor_cophenetic(dend2007c1, dend2009c1)
cr0710c1 <- cor_cophenetic(dend2007c1, dend2010c1)
cr0809c1 <- cor_cophenetic(dend2008c1, dend2009c1)
cr0810c1 <- cor_cophenetic(dend2008c1, dend2010c1)
cr0910c1 <- cor_cophenetic(dend2009c1, dend2010c1)

# Compute Common Nodes
cn0708c1 <- cor_common_nodes(dend2007c1, dend2008c1)
cn0709c1 <- cor_common_nodes(dend2007c1, dend2009c1)
cn0710c1 <- cor_common_nodes(dend2007c1, dend2010c1)
cn0809c1 <- cor_common_nodes(dend2008c1, dend2009c1)
cn0810c1 <- cor_common_nodes(dend2008c1, dend2010c1)
cn0910c1 <- cor_common_nodes(dend2009c1, dend2010c1)

# Generate summary of dendrogram comparisons and save as TXT file
sink("output-summary-case1.txt", append=FALSE, split=TRUE)
print("DENDLIST OBJECT")
print(list.dend78910c1)
print("GLOBAL COMPARISON OF DENDROGRAMS")
print(equal.dend78910c1)
print("CORRELATION MATRIX BETWEEN TREES")
print(cormat.dend78910c1)
print("BAKER'S GAMMA INDICES")
print(bg0708c1)
print(bg0709c1)
print(bg0710c1)
print(bg0809c1)
print(bg0810c1)
print(bg0910c1)
print("COPHENETIC CORRELATION")
print(cr0708c1)
print(cr0709c1)
print(cr0710c1)
print(cr0809c1)
print(cr0810c1)
print(cr0910c1)
print("COMMON NODES")
print(cn0708c1)
print(cn0709c1)
print(cn0710c1)
print(cn0809c1)
print(cn0810c1)
print(cn0910c1)
sink()

# CASE 2: POLARISATION + TOPOGRAPHIC

# Set working directory
setwd("/Users/dondealban/Image Processing/Thesis/R/3 clustering 2016/")

# Subset data by selecting variables
nlz2007c2 <- nlz2007[,c(40:45,48:53)]
nlz2008c2 <- nlz2008[,c(40:45,48:53)]
nlz2009c2 <- nlz2009[,c(40:45,48:53)]
nlz2010c2 <- nlz2010[,c(40:45,48:53)]

# Transpose matrix elements
tnlz2007c2 = t(nlz2007c2)
tnlz2008c2 = t(nlz2008c2)
tnlz2009c2 = t(nlz2009c2)
tnlz2010c2 = t(nlz2010c2)

# Hierarchical clustering using pvclust package
clust.nlz2007c2 <- pvclust(tnlz2007c2, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2008c2 <- pvclust(tnlz2008c2, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2009c2 <- pvclust(tnlz2009c2, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2010c2 <- pvclust(tnlz2010c2, method.hclust="average", method.dist="euclidean", nboot=1000)

# Plot dendrograms and save as PDF file
pdf("output-dendrogram-2007-case2.pdf", width=7, height=5.5)
clust.nlz2007c2 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2007 Case 2")
clust.nlz2007c2 %>% text
clust.nlz2007c2 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2008-case2.pdf", width=7, height=5.5)
clust.nlz2008c2 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2008 Case 2")
clust.nlz2008c2 %>% text
clust.nlz2008c2 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2009-case2.pdf", width=7, height=5.5)
clust.nlz2009c2 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2009 Case 2")
clust.nlz2009c2 %>% text
clust.nlz2009c2 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2010-case2.pdf", width=7, height=5.5)
clust.nlz2010c2 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2010 Case 2")
clust.nlz2010c2 %>% text
clust.nlz2010c2 %>% pvrect(alpha=0.95)
dev.off()

# Convert pvclust object variables to dendextend object variables
dend2007c2 <- as.dendrogram(clust.nlz2007c2)
dend2008c2 <- as.dendrogram(clust.nlz2008c2)
dend2009c2 <- as.dendrogram(clust.nlz2009c2)
dend2010c2 <- as.dendrogram(clust.nlz2010c2)

# Create a dendlist object from several dendrograms
list.dend78910c2 <- dendlist(dend2007c2, dend2008c2, dend2009c2, dend2010c2)

# Perform global comparison of two or more dendrograms to test if they are equal
equal.dend78910c2 <- all.equal(list.dend78910c2)

# Generate correlation matrix between a list of trees
cormat.dend78910c2 <- cor.dendlist(list.dend78910c2)

# Compute Baker's Gamma Index
bg0708c2 <- cor_bakers_gamma(dend2007c2, dend2008c2)
bg0709c2 <- cor_bakers_gamma(dend2007c2, dend2009c2)
bg0710c2 <- cor_bakers_gamma(dend2007c2, dend2010c2)
bg0809c2 <- cor_bakers_gamma(dend2008c2, dend2009c2)
bg0810c2 <- cor_bakers_gamma(dend2008c2, dend2010c2)
bg0910c2 <- cor_bakers_gamma(dend2009c2, dend2010c2)

# Compute Cophenetic Correlation coefficient
cr0708c2 <- cor_cophenetic(dend2007c2, dend2008c2)
cr0709c2 <- cor_cophenetic(dend2007c2, dend2009c2)
cr0710c2 <- cor_cophenetic(dend2007c2, dend2010c2)
cr0809c2 <- cor_cophenetic(dend2008c2, dend2009c2)
cr0810c2 <- cor_cophenetic(dend2008c2, dend2010c2)
cr0910c2 <- cor_cophenetic(dend2009c2, dend2010c2)

# Compute Common Nodes
cn0708c2 <- cor_common_nodes(dend2007c2, dend2008c2)
cn0709c2 <- cor_common_nodes(dend2007c2, dend2009c2)
cn0710c2 <- cor_common_nodes(dend2007c2, dend2010c2)
cn0809c2 <- cor_common_nodes(dend2008c2, dend2009c2)
cn0810c2 <- cor_common_nodes(dend2008c2, dend2010c2)
cn0910c2 <- cor_common_nodes(dend2009c2, dend2010c2)

# Generate summary of dendrogram comparisons and save as TXT file
sink("output-summary-case2.txt", append=FALSE, split=TRUE)
print("DENDLIST OBJECT")
print(list.dend78910c2)
print("GLOBAL COMPARISON OF DENDROGRAMS")
print(equal.dend78910c2)
print("CORRELATION MATRIX BETWEEN TREES")
print(cormat.dend78910c2)
print("BAKER'S GAMMA INDICES")
print(bg0708c2)
print(bg0709c2)
print(bg0710c2)
print(bg0809c2)
print(bg0810c2)
print(bg0910c2)
print("COPHENETIC CORRELATION")
print(cr0708c2)
print(cr0709c2)
print(cr0710c2)
print(cr0809c2)
print(cr0810c2)
print(cr0910c2)
print("COMMON NODES")
print(cn0708c2)
print(cn0709c2)
print(cn0710c2)
print(cn0809c2)
print(cn0810c2)
print(cn0910c2)
sink()

# CASE 3: POLARISATION + TEXTURE

# Set working directory
setwd("/Users/dondealban/Image Processing/Thesis/R/3 clustering 2016/")

# Subset data by selecting variables
nlz2007c3 <- nlz2007[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:42,48:50)]
nlz2008c3 <- nlz2008[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:42,48:50)]
nlz2009c3 <- nlz2009[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:42,48:50)]
nlz2010c3 <- nlz2010[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:42,48:50)]

# Transpose matrix elements
tnlz2007c3 = t(nlz2007c3)
tnlz2008c3 = t(nlz2008c3)
tnlz2009c3 = t(nlz2009c3)
tnlz2010c3 = t(nlz2010c3)

# Hierarchical clustering using pvclust package
clust.nlz2007c3 <- pvclust(tnlz2007c3, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2008c3 <- pvclust(tnlz2008c3, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2009c3 <- pvclust(tnlz2009c3, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2010c3 <- pvclust(tnlz2010c3, method.hclust="average", method.dist="euclidean", nboot=1000)

# Plot dendrograms and save as PDF file
pdf("output-dendrogram-2007-case3.pdf", width=7, height=5.5)
clust.nlz2007c3 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2007 Case 3")
clust.nlz2007c3 %>% text
clust.nlz2007c3 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2008-case3.pdf", width=7, height=5.5)
clust.nlz2008c3 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2008 Case 3")
clust.nlz2008c3 %>% text
clust.nlz2008c3 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2009-case3.pdf", width=7, height=5.5)
clust.nlz2009c3 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2009 Case 3")
clust.nlz2009c3 %>% text
clust.nlz2009c3 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2010-case3.pdf", width=7, height=5.5)
clust.nlz2010c3 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2010 Case 3")
clust.nlz2010c3 %>% text
clust.nlz2010c3 %>% pvrect(alpha=0.95)
dev.off()

# Convert pvclust object variables to dendextend object variables
dend2007c3 <- as.dendrogram(clust.nlz2007c3)
dend2008c3 <- as.dendrogram(clust.nlz2008c3)
dend2009c3 <- as.dendrogram(clust.nlz2009c3)
dend2010c3 <- as.dendrogram(clust.nlz2010c3)

# Create a dendlist object from several dendrograms
list.dend78910c3 <- dendlist(dend2007c3, dend2008c3, dend2009c3, dend2010c3)

# Perform global comparison of two or more dendrograms to test if they are equal
equal.dend78910c3 <- all.equal(list.dend78910c3)

# Generate correlation matrix between a list of trees
cormat.dend78910c3 <- cor.dendlist(list.dend78910c3)

# Compute Baker's Gamma Index
bg0708c3 <- cor_bakers_gamma(dend2007c3, dend2008c3)
bg0709c3 <- cor_bakers_gamma(dend2007c3, dend2009c3)
bg0710c3 <- cor_bakers_gamma(dend2007c3, dend2010c3)
bg0809c3 <- cor_bakers_gamma(dend2008c3, dend2009c3)
bg0810c3 <- cor_bakers_gamma(dend2008c3, dend2010c3)
bg0910c3 <- cor_bakers_gamma(dend2009c3, dend2010c3)

# Compute Cophenetic Correlation coefficient
cr0708c3 <- cor_cophenetic(dend2007c3, dend2008c3)
cr0709c3 <- cor_cophenetic(dend2007c3, dend2009c3)
cr0710c3 <- cor_cophenetic(dend2007c3, dend2010c3)
cr0809c3 <- cor_cophenetic(dend2008c3, dend2009c3)
cr0810c3 <- cor_cophenetic(dend2008c3, dend2010c3)
cr0910c3 <- cor_cophenetic(dend2009c3, dend2010c3)

# Compute Common Nodes
cn0708c3 <- cor_common_nodes(dend2007c3, dend2008c3)
cn0709c3 <- cor_common_nodes(dend2007c3, dend2009c3)
cn0710c3 <- cor_common_nodes(dend2007c3, dend2010c3)
cn0809c3 <- cor_common_nodes(dend2008c3, dend2009c3)
cn0810c3 <- cor_common_nodes(dend2008c3, dend2010c3)
cn0910c3 <- cor_common_nodes(dend2009c3, dend2010c3)

# Generate summary of dendrogram comparisons and save as TXT file
sink("output-summary-case3.txt", append=FALSE, split=TRUE)
print("DENDLIST OBJECT")
print(list.dend78910c3)
print("GLOBAL COMPARISON OF DENDROGRAMS")
print(equal.dend78910c3)
print("CORRELATION MATRIX BETWEEN TREES")
print(cormat.dend78910c3)
print("BAKER'S GAMMA INDICES")
print(bg0708c3)
print(bg0709c3)
print(bg0710c3)
print(bg0809c3)
print(bg0810c3)
print(bg0910c3)
print("COPHENETIC CORRELATION")
print(cr0708c3)
print(cr0709c3)
print(cr0710c3)
print(cr0809c3)
print(cr0810c3)
print(cr0910c3)
print("COMMON NODES")
print(cn0708c3)
print(cn0709c3)
print(cn0710c3)
print(cn0809c3)
print(cn0810c3)
print(cn0910c3)
sink()

# CASE 4: POLARISATION + TEXTURE

# Set working directory
setwd("/Users/dondealban/Image Processing/Thesis/R/3 clustering 2016/")

# Subset data by selecting variables
nlz2007c4 <- nlz2007[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:42,48:50)]
nlz2008c4 <- nlz2008[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:42,48:50)]
nlz2009c4 <- nlz2009[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:42,48:50)]
nlz2010c4 <- nlz2010[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:42,48:50)]

# Transpose matrix elements
tnlz2007c4 = t(nlz2007c4)
tnlz2008c4 = t(nlz2008c4)
tnlz2009c4 = t(nlz2009c4)
tnlz2010c4 = t(nlz2010c4)

# Hierarchical clustering using pvclust package
clust.nlz2007c4 <- pvclust(tnlz2007c4, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2008c4 <- pvclust(tnlz2008c4, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2009c4 <- pvclust(tnlz2009c4, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2010c4 <- pvclust(tnlz2010c4, method.hclust="average", method.dist="euclidean", nboot=1000)

# Plot dendrograms and save as PDF file
pdf("output-dendrogram-2007-case4.pdf", width=7, height=5.5)
clust.nlz2007c4 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2007 Case 4")
clust.nlz2007c4 %>% text
clust.nlz2007c4 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2008-case4.pdf", width=7, height=5.5)
clust.nlz2008c4 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2008 Case 4")
clust.nlz2008c4 %>% text
clust.nlz2008c4 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2009-case4.pdf", width=7, height=5.5)
clust.nlz2009c4 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2009 Case 4")
clust.nlz2009c4 %>% text
clust.nlz2009c4 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2010-case4.pdf", width=7, height=5.5)
clust.nlz2010c4 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2010 Case 4")
clust.nlz2010c4 %>% text
clust.nlz2010c4 %>% pvrect(alpha=0.95)
dev.off()

# Convert pvclust object variables to dendextend object variables
dend2007c4 <- as.dendrogram(clust.nlz2007c4)
dend2008c4 <- as.dendrogram(clust.nlz2008c4)
dend2009c4 <- as.dendrogram(clust.nlz2009c4)
dend2010c4 <- as.dendrogram(clust.nlz2010c4)

# Create a dendlist object from several dendrograms
list.dend78910c4 <- dendlist(dend2007c4, dend2008c4, dend2009c4, dend2010c4)

# Perform global comparison of two or more dendrograms to test if they are equal
equal.dend78910c4 <- all.equal(list.dend78910c4)

# Generate correlation matrix between a list of trees
cormat.dend78910c4 <- cor.dendlist(list.dend78910c4)

# Compute Baker's Gamma Index
bg0708c4 <- cor_bakers_gamma(dend2007c4, dend2008c4)
bg0709c4 <- cor_bakers_gamma(dend2007c4, dend2009c4)
bg0710c4 <- cor_bakers_gamma(dend2007c4, dend2010c4)
bg0809c4 <- cor_bakers_gamma(dend2008c4, dend2009c4)
bg0810c4 <- cor_bakers_gamma(dend2008c4, dend2010c4)
bg0910c4 <- cor_bakers_gamma(dend2009c4, dend2010c4)

# Compute Cophenetic Correlation coefficient
cr0708c4 <- cor_cophenetic(dend2007c4, dend2008c4)
cr0709c4 <- cor_cophenetic(dend2007c4, dend2009c4)
cr0710c4 <- cor_cophenetic(dend2007c4, dend2010c4)
cr0809c4 <- cor_cophenetic(dend2008c4, dend2009c4)
cr0810c4 <- cor_cophenetic(dend2008c4, dend2010c4)
cr0910c4 <- cor_cophenetic(dend2009c4, dend2010c4)

# Compute Common Nodes
cn0708c4 <- cor_common_nodes(dend2007c4, dend2008c4)
cn0709c4 <- cor_common_nodes(dend2007c4, dend2009c4)
cn0710c4 <- cor_common_nodes(dend2007c4, dend2010c4)
cn0809c4 <- cor_common_nodes(dend2008c4, dend2009c4)
cn0810c4 <- cor_common_nodes(dend2008c4, dend2010c4)
cn0910c4 <- cor_common_nodes(dend2009c4, dend2010c4)

# Generate summary of dendrogram comparisons and save as TXT file
sink("output-summary-case4.txt", append=FALSE, split=TRUE)
print("DENDLIST OBJECT")
print(list.dend78910c4)
print("GLOBAL COMPARISON OF DENDROGRAMS")
print(equal.dend78910c4)
print("CORRELATION MATRIX BETWEEN TREES")
print(cormat.dend78910c4)
print("BAKER'S GAMMA INDICES")
print(bg0708c4)
print(bg0709c4)
print(bg0710c4)
print(bg0809c4)
print(bg0810c4)
print(bg0910c4)
print("COPHENETIC CORRELATION")
print(cr0708c4)
print(cr0709c4)
print(cr0710c4)
print(cr0809c4)
print(cr0810c4)
print(cr0910c4)
print("COMMON NODES")
print(cn0708c4)
print(cn0709c4)
print(cn0710c4)
print(cn0809c4)
print(cn0810c4)
print(cn0910c4)
sink()

# CASE 5: POLARISATION + TOPOGRAPHIC + GEOMETRY

# Set working directory
setwd("/Users/dondealban/Image Processing/Thesis/R/3 clustering 2016/2016.02.19/")

# Subset data by selecting variables
nlz2007c5 <- nlz2007[,c(1:2,4:5,38:54)]
nlz2008c5 <- nlz2008[,c(1:2,4:5,38:54)]
nlz2009c5 <- nlz2009[,c(1:2,4:5,38:54)]
nlz2010c5 <- nlz2010[,c(1:2,4:5,38:54)]

# Transpose matrix elements
tnlz2007c5 = t(nlz2007c5)
tnlz2008c5 = t(nlz2008c5)
tnlz2009c5 = t(nlz2009c5)
tnlz2010c5 = t(nlz2010c5)

# Hierarchical clustering using pvclust package
clust.nlz2007c5 <- pvclust(tnlz2007c5, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2008c5 <- pvclust(tnlz2008c5, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2009c5 <- pvclust(tnlz2009c5, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2010c5 <- pvclust(tnlz2010c5, method.hclust="average", method.dist="euclidean", nboot=1000)

# Plot dendrograms and save as PDF file
pdf("output-dendrogram-2007-case5.pdf", width=7, height=5.5)
clust.nlz2007c5 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2007 Case 5")
clust.nlz2007c5 %>% text
clust.nlz2007c5 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2008-case5.pdf", width=7, height=5.5)
clust.nlz2008c5 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2008 Case 5")
clust.nlz2008c5 %>% text
clust.nlz2008c5 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2009-case5.pdf", width=7, height=5.5)
clust.nlz2009c5 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2009 Case 5")
clust.nlz2009c5 %>% text
clust.nlz2009c5 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2010-case5.pdf", width=7, height=5.5)
clust.nlz2010c5 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2010 Case 5")
clust.nlz2010c5 %>% text
clust.nlz2010c5 %>% pvrect(alpha=0.95)
dev.off()

# Convert pvclust object variables to dendextend object variables
dend2007c5 <- as.dendrogram(clust.nlz2007c5)
dend2008c5 <- as.dendrogram(clust.nlz2008c5)
dend2009c5 <- as.dendrogram(clust.nlz2009c5)
dend2010c5 <- as.dendrogram(clust.nlz2010c5)

# Create a dendlist object from several dendrograms
list.dend78910c5 <- dendlist(dend2007c5, dend2008c5, dend2009c5, dend2010c5)

# Perform global comparison of two or more dendrograms to test if they are equal
equal.dend78910c5 <- all.equal(list.dend78910c5)

# Generate correlation matrix between a list of trees
cormat.dend78910c5 <- cor.dendlist(list.dend78910c5)

# Compute Baker's Gamma Index
bg0708c5 <- cor_bakers_gamma(dend2007c5, dend2008c5)
bg0709c5 <- cor_bakers_gamma(dend2007c5, dend2009c5)
bg0710c5 <- cor_bakers_gamma(dend2007c5, dend2010c5)
bg0809c5 <- cor_bakers_gamma(dend2008c5, dend2009c5)
bg0810c5 <- cor_bakers_gamma(dend2008c5, dend2010c5)
bg0910c5 <- cor_bakers_gamma(dend2009c5, dend2010c5)

# Compute Cophenetic Correlation coefficient
cr0708c5 <- cor_cophenetic(dend2007c5, dend2008c5)
cr0709c5 <- cor_cophenetic(dend2007c5, dend2009c5)
cr0710c5 <- cor_cophenetic(dend2007c5, dend2010c5)
cr0809c5 <- cor_cophenetic(dend2008c5, dend2009c5)
cr0810c5 <- cor_cophenetic(dend2008c5, dend2010c5)
cr0910c5 <- cor_cophenetic(dend2009c5, dend2010c5)

# Compute Common Nodes
cn0708c5 <- cor_common_nodes(dend2007c5, dend2008c5)
cn0709c5 <- cor_common_nodes(dend2007c5, dend2009c5)
cn0710c5 <- cor_common_nodes(dend2007c5, dend2010c5)
cn0809c5 <- cor_common_nodes(dend2008c5, dend2009c5)
cn0810c5 <- cor_common_nodes(dend2008c5, dend2010c5)
cn0910c5 <- cor_common_nodes(dend2009c5, dend2010c5)

# Generate summary of dendrogram comparisons and save as TXT file
sink("output-summary-case5.txt", append=FALSE, split=TRUE)
print("DENDLIST OBJECT")
print(list.dend78910c5)
print("GLOBAL COMPARISON OF DENDROGRAMS")
print(equal.dend78910c5)
print("CORRELATION MATRIX BETWEEN TREES")
print(cormat.dend78910c5)
print("BAKER'S GAMMA INDICES")
print(bg0708c5)
print(bg0709c5)
print(bg0710c5)
print(bg0809c5)
print(bg0810c5)
print(bg0910c5)
print("COPHENETIC CORRELATION")
print(cr0708c5)
print(cr0709c5)
print(cr0710c5)
print(cr0809c5)
print(cr0810c5)
print(cr0910c5)
print("COMMON NODES")
print(cn0708c5)
print(cn0709c5)
print(cn0710c5)
print(cn0809c5)
print(cn0810c5)
print(cn0910c5)
sink()

# CASE 6: POLARISATION + TOPOGRAPHIC + TEXTURE

# Set working directory
setwd("/Users/dondealban/Image Processing/Thesis/R/3 clustering 2016/2016.02.19/")

# Subset data by selecting variables
nlz2007c6 <- nlz2007[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:45,48:53)]
nlz2008c6 <- nlz2008[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:45,48:53)]
nlz2009c6 <- nlz2009[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:45,48:53)]
nlz2010c6 <- nlz2010[,c(7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:37,40:45,48:53)]

# Transpose matrix elements
tnlz2007c6 = t(nlz2007c6)
tnlz2008c6 = t(nlz2008c6)
tnlz2009c6 = t(nlz2009c6)
tnlz2010c6 = t(nlz2010c6)

# Hierarchical clustering using pvclust package
clust.nlz2007c6 <- pvclust(tnlz2007c6, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2008c6 <- pvclust(tnlz2008c6, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2009c6 <- pvclust(tnlz2009c6, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2010c6 <- pvclust(tnlz2010c6, method.hclust="average", method.dist="euclidean", nboot=1000)

# Plot dendrograms and save as PDF file
pdf("output-dendrogram-2007-case6.pdf", width=7, height=5.5)
clust.nlz2007c6 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2007 Case 6")
clust.nlz2007c6 %>% text
clust.nlz2007c6 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2008-case6.pdf", width=7, height=5.5)
clust.nlz2008c6 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2008 Case 6")
clust.nlz2008c6 %>% text
clust.nlz2008c6 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2009-case6.pdf", width=7, height=5.5)
clust.nlz2009c6 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2009 Case 6")
clust.nlz2009c6 %>% text
clust.nlz2009c6 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2010-case6.pdf", width=7, height=5.5)
clust.nlz2010c6 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2010 Case 6")
clust.nlz2010c6 %>% text
clust.nlz2010c6 %>% pvrect(alpha=0.95)
dev.off()

# Convert pvclust object variables to dendextend object variables
dend2007c6 <- as.dendrogram(clust.nlz2007c6)
dend2008c6 <- as.dendrogram(clust.nlz2008c6)
dend2009c6 <- as.dendrogram(clust.nlz2009c6)
dend2010c6 <- as.dendrogram(clust.nlz2010c6)

# Create a dendlist object from several dendrograms
list.dend78910c6 <- dendlist(dend2007c6, dend2008c6, dend2009c6, dend2010c6)

# Perform global comparison of two or more dendrograms to test if they are equal
equal.dend78910c6 <- all.equal(list.dend78910c6)

# Generate correlation matrix between a list of trees
cormat.dend78910c6 <- cor.dendlist(list.dend78910c6)

# Compute Baker's Gamma Index
bg0708c6 <- cor_bakers_gamma(dend2007c6, dend2008c6)
bg0709c6 <- cor_bakers_gamma(dend2007c6, dend2009c6)
bg0710c6 <- cor_bakers_gamma(dend2007c6, dend2010c6)
bg0809c6 <- cor_bakers_gamma(dend2008c6, dend2009c6)
bg0810c6 <- cor_bakers_gamma(dend2008c6, dend2010c6)
bg0910c6 <- cor_bakers_gamma(dend2009c6, dend2010c6)

# Compute Cophenetic Correlation coefficient
cr0708c6 <- cor_cophenetic(dend2007c6, dend2008c6)
cr0709c6 <- cor_cophenetic(dend2007c6, dend2009c6)
cr0710c6 <- cor_cophenetic(dend2007c6, dend2010c6)
cr0809c6 <- cor_cophenetic(dend2008c6, dend2009c6)
cr0810c6 <- cor_cophenetic(dend2008c6, dend2010c6)
cr0910c6 <- cor_cophenetic(dend2009c6, dend2010c6)

# Compute Common Nodes
cn0708c6 <- cor_common_nodes(dend2007c6, dend2008c6)
cn0709c6 <- cor_common_nodes(dend2007c6, dend2009c6)
cn0710c6 <- cor_common_nodes(dend2007c6, dend2010c6)
cn0809c6 <- cor_common_nodes(dend2008c6, dend2009c6)
cn0810c6 <- cor_common_nodes(dend2008c6, dend2010c6)
cn0910c6 <- cor_common_nodes(dend2009c6, dend2010c6)

# Generate summary of dendrogram comparisons and save as TXT file
sink("output-summary-case6.txt", append=FALSE, split=TRUE)
print("DENDLIST OBJECT")
print(list.dend78910c6)
print("GLOBAL COMPARISON OF DENDROGRAMS")
print(equal.dend78910c6)
print("CORRELATION MATRIX BETWEEN TREES")
print(cormat.dend78910c6)
print("BAKER'S GAMMA INDICES")
print(bg0708c6)
print(bg0709c6)
print(bg0710c6)
print(bg0809c6)
print(bg0810c6)
print(bg0910c6)
print("COPHENETIC CORRELATION")
print(cr0708c6)
print(cr0709c6)
print(cr0710c6)
print(cr0809c6)
print(cr0810c6)
print(cr0910c6)
print("COMMON NODES")
print(cn0708c6)
print(cn0709c6)
print(cn0710c6)
print(cn0809c6)
print(cn0810c6)
print(cn0910c6)
sink()

# CASE 7: POLARISATION + GEOMETRY + TEXTURE

# Set working directory
setwd("/Users/dondealban/Image Processing/Thesis/R/3 clustering 2016/2016.02.19/")

# Subset data by selecting variables
nlz2007c7 <- nlz2007[,c(1:2,4:5,7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:42,46:50,54)]
nlz2008c7 <- nlz2008[,c(1:2,4:5,7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:42,46:50,54)]
nlz2009c7 <- nlz2009[,c(1:2,4:5,7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:42,46:50,54)]
nlz2010c7 <- nlz2010[,c(1:2,4:5,7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:42,46:50,54)]

# Transpose matrix elements
tnlz2007c7 = t(nlz2007c7)
tnlz2008c7 = t(nlz2008c7)
tnlz2009c7 = t(nlz2009c7)
tnlz2010c7 = t(nlz2010c7)

# Hierarchical clustering using pvclust package
clust.nlz2007c7 <- pvclust(tnlz2007c7, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2008c7 <- pvclust(tnlz2008c7, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2009c7 <- pvclust(tnlz2009c7, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2010c7 <- pvclust(tnlz2010c7, method.hclust="average", method.dist="euclidean", nboot=1000)

# Plot dendrograms and save as PDF file
pdf("output-dendrogram-2007-case7.pdf", width=7, height=5.5)
clust.nlz2007c7 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2007 Case 7")
clust.nlz2007c7 %>% text
clust.nlz2007c7 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2008-case7.pdf", width=7, height=5.5)
clust.nlz2008c7 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2008 Case 7")
clust.nlz2008c7 %>% text
clust.nlz2008c7 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2009-case7.pdf", width=7, height=5.5)
clust.nlz2009c7 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2009 Case 7")
clust.nlz2009c7 %>% text
clust.nlz2009c7 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2010-case7.pdf", width=7, height=5.5)
clust.nlz2010c7 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2010 Case 7")
clust.nlz2010c7 %>% text
clust.nlz2010c7 %>% pvrect(alpha=0.95)
dev.off()

# Convert pvclust object variables to dendextend object variables
dend2007c7 <- as.dendrogram(clust.nlz2007c7)
dend2008c7 <- as.dendrogram(clust.nlz2008c7)
dend2009c7 <- as.dendrogram(clust.nlz2009c7)
dend2010c7 <- as.dendrogram(clust.nlz2010c7)

# Create a dendlist object from several dendrograms
list.dend78910c7 <- dendlist(dend2007c7, dend2008c7, dend2009c7, dend2010c7)

# Perform global comparison of two or more dendrograms to test if they are equal
equal.dend78910c7 <- all.equal(list.dend78910c7)

# Generate correlation matrix between a list of trees
cormat.dend78910c7 <- cor.dendlist(list.dend78910c7)

# Compute Baker's Gamma Index
bg0708c7 <- cor_bakers_gamma(dend2007c7, dend2008c7)
bg0709c7 <- cor_bakers_gamma(dend2007c7, dend2009c7)
bg0710c7 <- cor_bakers_gamma(dend2007c7, dend2010c7)
bg0809c7 <- cor_bakers_gamma(dend2008c7, dend2009c7)
bg0810c7 <- cor_bakers_gamma(dend2008c7, dend2010c7)
bg0910c7 <- cor_bakers_gamma(dend2009c7, dend2010c7)

# Compute Cophenetic Correlation coefficient
cr0708c7 <- cor_cophenetic(dend2007c7, dend2008c7)
cr0709c7 <- cor_cophenetic(dend2007c7, dend2009c7)
cr0710c7 <- cor_cophenetic(dend2007c7, dend2010c7)
cr0809c7 <- cor_cophenetic(dend2008c7, dend2009c7)
cr0810c7 <- cor_cophenetic(dend2008c7, dend2010c7)
cr0910c7 <- cor_cophenetic(dend2009c7, dend2010c7)

# Compute Common Nodes
cn0708c7 <- cor_common_nodes(dend2007c7, dend2008c7)
cn0709c7 <- cor_common_nodes(dend2007c7, dend2009c7)
cn0710c7 <- cor_common_nodes(dend2007c7, dend2010c7)
cn0809c7 <- cor_common_nodes(dend2008c7, dend2009c7)
cn0810c7 <- cor_common_nodes(dend2008c7, dend2010c7)
cn0910c7 <- cor_common_nodes(dend2009c7, dend2010c7)

# Generate summary of dendrogram comparisons and save as TXT file
sink("output-summary-case7.txt", append=FALSE, split=TRUE)
print("DENDLIST OBJECT")
print(list.dend78910c7)
print("GLOBAL COMPARISON OF DENDROGRAMS")
print(equal.dend78910c7)
print("CORRELATION MATRIX BETWEEN TREES")
print(cormat.dend78910c7)
print("BAKER'S GAMMA INDICES")
print(bg0708c7)
print(bg0709c7)
print(bg0710c7)
print(bg0809c7)
print(bg0810c7)
print(bg0910c7)
print("COPHENETIC CORRELATION")
print(cr0708c7)
print(cr0709c7)
print(cr0710c7)
print(cr0809c7)
print(cr0810c7)
print(cr0910c7)
print("COMMON NODES")
print(cn0708c7)
print(cn0709c7)
print(cn0710c7)
print(cn0809c7)
print(cn0810c7)
print(cn0910c7)
sink()

# CASE 8: POLARISATION + TOPOGRAPHIC + GEOMETRY + TEXTURE

# Set working directory
setwd("/Users/dondealban/Image Processing/Thesis/R/3 clustering 2016/2016.02.19/")

# Subset data by selecting variables
nlz2007c8 <- nlz2007[,c(1:2,4:5,7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:54)]
nlz2008c8 <- nlz2008[,c(1:2,4:5,7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:54)]
nlz2009c8 <- nlz2009[,c(1:2,4:5,7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:54)]
nlz2010c8 <- nlz2010[,c(1:2,4:5,7:9,11:13,15:17,19:21,23:25,27:29,31:33,35:54)]

# Transpose matrix elements
tnlz2007c8 = t(nlz2007c8)
tnlz2008c8 = t(nlz2008c8)
tnlz2009c8 = t(nlz2009c8)
tnlz2010c8 = t(nlz2010c8)

# Hierarchical clustering using pvclust package
clust.nlz2007c8 <- pvclust(tnlz2007c8, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2008c8 <- pvclust(tnlz2008c8, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2009c8 <- pvclust(tnlz2009c8, method.hclust="average", method.dist="euclidean", nboot=1000)
clust.nlz2010c8 <- pvclust(tnlz2010c8, method.hclust="average", method.dist="euclidean", nboot=1000)

# Plot dendrograms and save as PDF file
pdf("output-dendrogram-2007-case8.pdf", width=7, height=5.5)
clust.nlz2007c8 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2007 Case 8")
clust.nlz2007c8 %>% text
clust.nlz2007c8 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2008-case8.pdf", width=7, height=5.5)
clust.nlz2008c8 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2008 Case 8")
clust.nlz2008c8 %>% text
clust.nlz2008c8 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2009-case8.pdf", width=7, height=5.5)
clust.nlz2009c8 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2009 Case 8")
clust.nlz2009c8 %>% text
clust.nlz2009c8 %>% pvrect(alpha=0.95)
dev.off()
pdf("output-dendrogram-2010-case8.pdf", width=7, height=5.5)
clust.nlz2010c8 %>% as.dendrogram %>% hang.dendrogram %>% plot(main = "Dendrogram: 2010 Case 8")
clust.nlz2010c8 %>% text
clust.nlz2010c8 %>% pvrect(alpha=0.95)
dev.off()

# Convert pvclust object variables to dendextend object variables
dend2007c8 <- as.dendrogram(clust.nlz2007c8)
dend2008c8 <- as.dendrogram(clust.nlz2008c8)
dend2009c8 <- as.dendrogram(clust.nlz2009c8)
dend2010c8 <- as.dendrogram(clust.nlz2010c8)

# Create a dendlist object from several dendrograms
list.dend78910c8 <- dendlist(dend2007c8, dend2008c8, dend2009c8, dend2010c8)

# Perform global comparison of two or more dendrograms to test if they are equal
equal.dend78910c8 <- all.equal(list.dend78910c8)

# Generate correlation matrix between a list of trees
cormat.dend78910c8 <- cor.dendlist(list.dend78910c8)

# Compute Baker's Gamma Index
bg0708c8 <- cor_bakers_gamma(dend2007c8, dend2008c8)
bg0709c8 <- cor_bakers_gamma(dend2007c8, dend2009c8)
bg0710c8 <- cor_bakers_gamma(dend2007c8, dend2010c8)
bg0809c8 <- cor_bakers_gamma(dend2008c8, dend2009c8)
bg0810c8 <- cor_bakers_gamma(dend2008c8, dend2010c8)
bg0910c8 <- cor_bakers_gamma(dend2009c8, dend2010c8)

# Compute Cophenetic Correlation coefficient
cr0708c8 <- cor_cophenetic(dend2007c8, dend2008c8)
cr0709c8 <- cor_cophenetic(dend2007c8, dend2009c8)
cr0710c8 <- cor_cophenetic(dend2007c8, dend2010c8)
cr0809c8 <- cor_cophenetic(dend2008c8, dend2009c8)
cr0810c8 <- cor_cophenetic(dend2008c8, dend2010c8)
cr0910c8 <- cor_cophenetic(dend2009c8, dend2010c8)

# Compute Common Nodes
cn0708c8 <- cor_common_nodes(dend2007c8, dend2008c8)
cn0709c8 <- cor_common_nodes(dend2007c8, dend2009c8)
cn0710c8 <- cor_common_nodes(dend2007c8, dend2010c8)
cn0809c8 <- cor_common_nodes(dend2008c8, dend2009c8)
cn0810c8 <- cor_common_nodes(dend2008c8, dend2010c8)
cn0910c8 <- cor_common_nodes(dend2009c8, dend2010c8)

# Generate summary of dendrogram comparisons and save as TXT file
sink("output-summary-case8.txt", append=FALSE, split=TRUE)
print("DENDLIST OBJECT")
print(list.dend78910c8)
print("GLOBAL COMPARISON OF DENDROGRAMS")
print(equal.dend78910c8)
print("CORRELATION MATRIX BETWEEN TREES")
print(cormat.dend78910c8)
print("BAKER'S GAMMA INDICES")
print(bg0708c8)
print(bg0709c8)
print(bg0710c8)
print(bg0809c8)
print(bg0810c8)
print(bg0910c8)
print("COPHENETIC CORRELATION")
print(cr0708c8)
print(cr0709c8)
print(cr0710c8)
print(cr0809c8)
print(cr0810c8)
print(cr0910c8)
print("COMMON NODES")
print(cn0708c8)
print(cn0709c8)
print(cn0710c8)
print(cn0809c8)
print(cn0810c8)
print(cn0910c8)
sink()
