# This R script implements decision tree classification using tree package.
# The decision tree classification aims to grow a tree by binary recursive partitioning
# using the predictor variables or features derived from image object statistics 
# generated by eCognition (at scale 10) and then choosing splits by land/forest cover types.
#
# Script By:      Jose Don T. De Alban
# Date Created:   09 May 2015
# Last Modified:  23 Feb 2016

# Set working directory
# Note: Need to change the path name as necessary
setwd("/Users/dondealban/Image Processing/Thesis/R/4 tree classification/")

# Load the required R libraries
library(tree)

# Read data, define variables, and store data in variables
dat2007 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2007.csv", header=TRUE, sep=",")
#dat2008 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2008.csv", header=TRUE, sep=",")
#dat2009 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2009.csv", header=TRUE, sep=",")
#dat2010 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2010.csv", header=TRUE, sep=",")

# Insert new standard variables for classification levels 1,2,3 for multi-year data

# Level1: land - water
# 2007
dat2007$LC1[dat2007$LCCode=="WNOW" | dat2007$LCCode=="WNRB" | dat2007$LCCode=="WNSS"] <- "WTR"
dat2007$LC1[dat2007$LC1!="WTR"] <- "LND"
# 2008
dat2008$LC1[dat2008$LCCode=="WNOW" | dat2008$LCCode=="WNRB" | dat2008$LCCode=="WNSS"] <- "WTR"
dat2008$LC1[dat2008$LC1!="WTR"] <- "LND"
# 2009
dat2009$LC1[dat2009$LCCode=="WNOW" | dat2009$LCCode=="WNRB" | dat2009$LCCode=="WNSS"] <- "WTR"
dat2009$LC1[dat2009$LC1!="WTR"] <- "LND"
# 2010
dat2010$LC1[dat2010$LCCode=="WNOW" | dat2010$LCCode=="WNRB" | dat2010$LCCode=="WNSS"] <- "WTR"
dat2010$LC1[dat2010$LC1!="WTR"] <- "LND"

# Level2: vegetation - non-vegetation
# 2007
dat2007$LC2[dat2007$LC1=="WTR"] <- "WTR"
dat2007$LC2[dat2007$LC1!="WTR" & dat2007$LCCode=="LNBU"] <- "NVG"
dat2007$LC2[dat2007$LC1!="WTR" & dat2007$LC2!="NVG"] <- "VEG"
# 2008
dat2008$LC2[dat2008$LC1=="WTR"] <- "WTR"
dat2008$LC2[dat2008$LC1!="WTR" & dat2008$LCCode=="LNBU"] <- "NVG"
dat2008$LC2[dat2008$LC1!="WTR" & dat2008$LC2!="NVG"] <- "VEG"
# 2009
dat2009$LC2[dat2009$LC1=="WTR"] <- "WTR"
dat2009$LC2[dat2009$LC1!="WTR" & dat2009$LCCode=="LNBU"] <- "NVG"
dat2009$LC2[dat2009$LC1!="WTR" & dat2009$LC2!="NVG"] <- "VEG"
# 2010
dat2010$LC2[dat2010$LC1=="WTR"] <- "WTR"
dat2010$LC2[dat2010$LC1!="WTR" & dat2010$LCCode=="LNBU"] <- "NVG"
dat2010$LC2[dat2010$LC1!="WTR" & dat2010$LC2!="NVG"] <- "VEG"

# Level3: forest - non-forest
# 2007
dat2007$LC3[dat2007$LC2=="WTR"] <- "WTR"
dat2007$LC3[dat2007$LC2=="NVG"] <- "NVG"
dat2007$LC3[dat2007$LCCode=="LVGR" | dat2007$LCCode=="LVSH" | dat2007$LCCode=="LVWG"] <- "NFR"
dat2007$LC3[dat2007$LC3!="WTR" & dat2007$LC3!="NVG" & dat2007$LC3!="NFR"] <- "FOR"
# 2008
dat2008$LC3[dat2008$LC2=="WTR"] <- "WTR"
dat2008$LC3[dat2008$LC2=="NVG"] <- "NVG"
dat2008$LC3[dat2008$LCCode=="LVGR" | dat2008$LCCode=="LVSH" | dat2008$LCCode=="LVWG"] <- "NFR"
dat2008$LC3[dat2008$LC3!="WTR" & dat2008$LC3!="NVG" & dat2008$LC3!="NFR"] <- "FOR"
# 2009
dat2009$LC3[dat2009$LC2=="WTR"] <- "WTR"
dat2009$LC3[dat2009$LC2=="NVG"] <- "NVG"
dat2009$LC3[dat2009$LCCode=="LVGR" | dat2009$LCCode=="LVSH" | dat2009$LCCode=="LVWG"] <- "NFR"
dat2009$LC3[dat2009$LC3!="WTR" & dat2009$LC3!="NVG" & dat2009$LC3!="NFR"] <- "FOR"
# 2010
dat2010$LC3[dat2010$LC2=="WTR"] <- "WTR"
dat2010$LC3[dat2010$LC2=="NVG"] <- "NVG"
dat2010$LC3[dat2010$LCCode=="LVGR" | dat2010$LCCode=="LVSH" | dat2010$LCCode=="LVWG"] <- "NFR"
dat2010$LC3[dat2010$LC3!="WTR" & dat2010$LC3!="NVG" & dat2010$LC3!="NFR"] <- "FOR"

# Select observations per classification level and store selected data in variables
nlz.lc1  <- nlz
nlz.lc2  <- subset(nlz, subset=(LC1=="Land"))
nlz.lc3  <- subset(nlz, subset=(LC2=="Veg"))
nlz.lc4  <- subset(nlz, subset=(LC3=="Forest"))
nlz.lc5  <- subset(nlz, subset=(LC4=="FG1"))
nlz.lc6  <- subset(nlz, subset=(LC5=="FG2"))
nlz.lc7a <- subset(nlz, subset=(LC6=="FG3"))
nlz.lc7b <- subset(nlz, subset=(LC6=="FG4"))
nlz.lc8  <- subset(nlz, subset=(LC7A=="FG5"))
nlz.lc9  <- subset(nlz, subset=(LC8=="FG6"))
nlz.lc10 <- subset(nlz, subset=(LC9=="FG7"))

# Execute tree function using specified classification level and predictor variables
tree.nlz.lc1  <- tree(factor(LC1)  ~ Mean.HH + Mean.HV + Mean.RAT + Mean.DEM + Mean.Slope + SD.HH + SD.HV + SD.RAT + SD.DEM + SD.Slope + Area.Pixel + Asymmetry + Brightness + Compactness + EllipticFit + GLCM.AngSecMom + GLCM.Contrast + GLCM.Correlation + GLCM.Dissimilarity + GLCM.Entropy + GLCM.Homogeneity + GLCM.Mean + GLCM.SD + Length.Pixel + LengthWidthRatio + RectangularFit + Roundness + Width.Pixel, nlz.lc1)
tree.nlz.lc2  <- tree(factor(LC2)  ~ Mean.HH + Mean.HV + Mean.RAT + Mean.DEM + Mean.Slope + SD.HH + SD.HV + SD.RAT + SD.DEM + SD.Slope + Area.Pixel + Asymmetry + Brightness + Compactness + EllipticFit + GLCM.AngSecMom + GLCM.Contrast + GLCM.Correlation + GLCM.Dissimilarity + GLCM.Entropy + GLCM.Homogeneity + GLCM.Mean + GLCM.SD + Length.Pixel + LengthWidthRatio + RectangularFit + Roundness + Width.Pixel, nlz.lc2)
tree.nlz.lc3  <- tree(factor(LC3)  ~ Mean.HH + Mean.HV + Mean.RAT + Mean.DEM + Mean.Slope + SD.HH + SD.HV + SD.RAT + SD.DEM + SD.Slope + Area.Pixel + Asymmetry + Brightness + Compactness + EllipticFit + GLCM.AngSecMom + GLCM.Contrast + GLCM.Correlation + GLCM.Dissimilarity + GLCM.Entropy + GLCM.Homogeneity + GLCM.Mean + GLCM.SD + Length.Pixel + LengthWidthRatio + RectangularFit + Roundness + Width.Pixel, nlz.lc3)
tree.nlz.lc4  <- tree(factor(LC4)  ~ Mean.HH + Mean.HV + Mean.RAT + Mean.DEM + Mean.Slope + SD.HH + SD.HV + SD.RAT + SD.DEM + SD.Slope + Area.Pixel + Asymmetry + Brightness + Compactness + EllipticFit + GLCM.AngSecMom + GLCM.Contrast + GLCM.Correlation + GLCM.Dissimilarity + GLCM.Entropy + GLCM.Homogeneity + GLCM.Mean + GLCM.SD + Length.Pixel + LengthWidthRatio + RectangularFit + Roundness + Width.Pixel, nlz.lc4)
tree.nlz.lc5  <- tree(factor(LC5)  ~ Mean.HH + Mean.HV + Mean.RAT + Mean.DEM + Mean.Slope + SD.HH + SD.HV + SD.RAT + SD.DEM + SD.Slope + Area.Pixel + Asymmetry + Brightness + Compactness + EllipticFit + GLCM.AngSecMom + GLCM.Contrast + GLCM.Correlation + GLCM.Dissimilarity + GLCM.Entropy + GLCM.Homogeneity + GLCM.Mean + GLCM.SD + Length.Pixel + LengthWidthRatio + RectangularFit + Roundness + Width.Pixel, nlz.lc5)
tree.nlz.lc6  <- tree(factor(LC6)  ~ Mean.HH + Mean.HV + Mean.RAT + Mean.DEM + Mean.Slope + SD.HH + SD.HV + SD.RAT + SD.DEM + SD.Slope + Area.Pixel + Asymmetry + Brightness + Compactness + EllipticFit + GLCM.AngSecMom + GLCM.Contrast + GLCM.Correlation + GLCM.Dissimilarity + GLCM.Entropy + GLCM.Homogeneity + GLCM.Mean + GLCM.SD + Length.Pixel + LengthWidthRatio + RectangularFit + Roundness + Width.Pixel, nlz.lc6)
tree.nlz.lc7a <- tree(factor(LC7A) ~ Mean.HH + Mean.HV + Mean.RAT + Mean.DEM + Mean.Slope + SD.HH + SD.HV + SD.RAT + SD.DEM + SD.Slope + Area.Pixel + Asymmetry + Brightness + Compactness + EllipticFit + GLCM.AngSecMom + GLCM.Contrast + GLCM.Correlation + GLCM.Dissimilarity + GLCM.Entropy + GLCM.Homogeneity + GLCM.Mean + GLCM.SD + Length.Pixel + LengthWidthRatio + RectangularFit + Roundness + Width.Pixel, nlz.lc7a)
tree.nlz.lc7b <- tree(factor(LC7B) ~ Mean.HH + Mean.HV + Mean.RAT + Mean.DEM + Mean.Slope + SD.HH + SD.HV + SD.RAT + SD.DEM + SD.Slope + Area.Pixel + Asymmetry + Brightness + Compactness + EllipticFit + GLCM.AngSecMom + GLCM.Contrast + GLCM.Correlation + GLCM.Dissimilarity + GLCM.Entropy + GLCM.Homogeneity + GLCM.Mean + GLCM.SD + Length.Pixel + LengthWidthRatio + RectangularFit + Roundness + Width.Pixel, nlz.lc7b)
tree.nlz.lc8  <- tree(factor(LC8)  ~ Mean.HH + Mean.HV + Mean.RAT + Mean.DEM + Mean.Slope + SD.HH + SD.HV + SD.RAT + SD.DEM + SD.Slope + Area.Pixel + Asymmetry + Brightness + Compactness + EllipticFit + GLCM.AngSecMom + GLCM.Contrast + GLCM.Correlation + GLCM.Dissimilarity + GLCM.Entropy + GLCM.Homogeneity + GLCM.Mean + GLCM.SD + Length.Pixel + LengthWidthRatio + RectangularFit + Roundness + Width.Pixel, nlz.lc8)
tree.nlz.lc9  <- tree(factor(LC9)  ~ Mean.HH + Mean.HV + Mean.RAT + Mean.DEM + Mean.Slope + SD.HH + SD.HV + SD.RAT + SD.DEM + SD.Slope + Area.Pixel + Asymmetry + Brightness + Compactness + EllipticFit + GLCM.AngSecMom + GLCM.Contrast + GLCM.Correlation + GLCM.Dissimilarity + GLCM.Entropy + GLCM.Homogeneity + GLCM.Mean + GLCM.SD + Length.Pixel + LengthWidthRatio + RectangularFit + Roundness + Width.Pixel, nlz.lc9)
tree.nlz.lc10 <- tree(factor(LC10) ~ Mean.HH + Mean.HV + Mean.RAT + Mean.DEM + Mean.Slope + SD.HH + SD.HV + SD.RAT + SD.DEM + SD.Slope + Area.Pixel + Asymmetry + Brightness + Compactness + EllipticFit + GLCM.AngSecMom + GLCM.Contrast + GLCM.Correlation + GLCM.Dissimilarity + GLCM.Entropy + GLCM.Homogeneity + GLCM.Mean + GLCM.SD + Length.Pixel + LengthWidthRatio + RectangularFit + Roundness + Width.Pixel, nlz.lc10)

# Generate tree summary and misclassification statistics and save as TXT file
sink("output-tree-summary-lc1.txt", append=FALSE, split=TRUE)
print(tree.nlz.lc1)
print(summary(tree.nlz.lc1))
print(misclass.tree(tree.nlz.lc1, detail=TRUE))
sink()
sink("output-tree-summary-lc2.txt", append=FALSE, split=TRUE)
print(tree.nlz.lc2)
print(summary(tree.nlz.lc2))
print(misclass.tree(tree.nlz.lc2, detail=TRUE))
sink()
sink("output-tree-summary-lc3.txt", append=FALSE, split=TRUE)
print(tree.nlz.lc3)
print(summary(tree.nlz.lc3))
print(misclass.tree(tree.nlz.lc3, detail=TRUE))
sink()
sink("output-tree-summary-lc4.txt", append=FALSE, split=TRUE)
print(tree.nlz.lc4)
print(summary(tree.nlz.lc4))
print(misclass.tree(tree.nlz.lc4, detail=TRUE))
sink()
sink("output-tree-summary-lc5.txt", append=FALSE, split=TRUE)
print(tree.nlz.lc5)
print(summary(tree.nlz.lc5))
print(misclass.tree(tree.nlz.lc5, detail=TRUE))
sink()
sink("output-tree-summary-lc6.txt", append=FALSE, split=TRUE)
print(tree.nlz.lc6)
print(summary(tree.nlz.lc6))
print(misclass.tree(tree.nlz.lc6, detail=TRUE))
sink()
sink("output-tree-summary-lc7a.txt", append=FALSE, split=TRUE)
print(tree.nlz.lc7a)
print(summary(tree.nlz.lc7a))
print(misclass.tree(tree.nlz.lc7a, detail=TRUE))
sink()
sink("output-tree-summary-lc7b.txt", append=FALSE, split=TRUE)
print(tree.nlz.lc7b)
print(summary(tree.nlz.lc7b))
print(misclass.tree(tree.nlz.lc7b, detail=TRUE))
sink()
sink("output-tree-summary-lc8.txt", append=FALSE, split=TRUE)
print(tree.nlz.lc8)
print(summary(tree.nlz.lc8))
print(misclass.tree(tree.nlz.lc8, detail=TRUE))
sink()
sink("output-tree-summary-lc9.txt", append=FALSE, split=TRUE)
print(tree.nlz.lc9)
print(summary(tree.nlz.lc9))
print(misclass.tree(tree.nlz.lc9, detail=TRUE))
sink()
sink("output-tree-summary-lc10.txt", append=FALSE, split=TRUE)
print(tree.nlz.lc10)
print(summary(tree.nlz.lc10))
print(misclass.tree(tree.nlz.lc10, detail=TRUE))
sink()

# Plot tree object and save as PNG file
png("output-tree-lc1.png", width=700, height=500)
plot(tree.nlz.lc1)
text(tree.nlz.lc1, cex=0.70)
dev.off()
png("output-tree-lc2.png", width=700, height=500)
plot(tree.nlz.lc2)
text(tree.nlz.lc2, cex=0.70)
dev.off()
png("output-tree-lc3.png", width=700, height=500)
plot(tree.nlz.lc3)
text(tree.nlz.lc3, cex=0.70)
dev.off()
png("output-tree-lc4.png", width=700, height=500)
plot(tree.nlz.lc4)
text(tree.nlz.lc4, cex=0.70)
dev.off()
png("output-tree-lc5.png", width=700, height=500)
plot(tree.nlz.lc5)
text(tree.nlz.lc5, cex=0.70)
dev.off()
png("output-tree-lc6.png", width=700, height=500)
plot(tree.nlz.lc6)
text(tree.nlz.lc6, cex=0.70)
dev.off()
png("output-tree-lc7a.png", width=700, height=500)
plot(tree.nlz.lc7a)
text(tree.nlz.lc7a, cex=0.70)
dev.off()
png("output-tree-lc7b.png", width=700, height=500)
plot(tree.nlz.lc7b)
text(tree.nlz.lc7b, cex=0.70)
dev.off()
png("output-tree-lc8.png", width=700, height=500)
plot(tree.nlz.lc8)
text(tree.nlz.lc8, cex=0.70)
dev.off()
png("output-tree-lc9.png", width=700, height=500)
plot(tree.nlz.lc9)
text(tree.nlz.lc9, cex=0.70)
dev.off()
png("output-tree-lc10.png", width=700, height=500)
plot(tree.nlz.lc10)
text(tree.nlz.lc10, cex=0.70)
dev.off()

# Plot cross-validation graph and save as PNG file
png("output-cv-lc1.png", width=700, height=500)
plot(cv.tree(tree.nlz.lc1))
dev.off()
png("output-cv-lc2.png", width=700, height=500)
plot(cv.tree(tree.nlz.lc2))
dev.off()
png("output-cv-lc3.png", width=700, height=500)
plot(cv.tree(tree.nlz.lc3))
dev.off()
png("output-cv-lc4.png", width=700, height=500)
plot(cv.tree(tree.nlz.lc4))
dev.off()
png("output-cv-lc5.png", width=700, height=500)
plot(cv.tree(tree.nlz.lc5))
dev.off()
png("output-cv-lc6.png", width=700, height=500)
plot(cv.tree(tree.nlz.lc6))
dev.off()
png("output-cv-lc7a.png", width=700, height=500)
plot(cv.tree(tree.nlz.lc7a))
dev.off()
png("output-cv-lc7b.png", width=700, height=500)
plot(cv.tree(tree.nlz.lc7b))
dev.off()
png("output-cv-lc8.png", width=700, height=500)
plot(cv.tree(tree.nlz.lc8))
dev.off()
png("output-cv-lc9.png", width=700, height=500)
plot(cv.tree(tree.nlz.lc9))
dev.off()
png("output-cv-lc10.png", width=700, height=500)
plot(cv.tree(tree.nlz.lc10))
dev.off()
