# This R script implements decision tree classification using tree package.
# The decision tree classification aims to grow a tree by binary recursive partitioning
# using the predictor variables or features derived from image object statistics 
# generated by eCognition (at scale 10) and then choosing splits by land/forest cover types.
#
# Script By:      Jose Don T. De Alban
# Date Created:   09 May 2015
# Last Modified:  23 Feb 2016

# Set working directory
# Note: Need to change the path name as necessary
setwd("/Users/dondealban/Image Processing/Thesis/R/4 tree classification/")

# Load the required R libraries
library(tree)

# Read data, define variables, and store data in variables
dat2007 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2007.csv", header=TRUE, sep=",")
dat2008 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2008.csv", header=TRUE, sep=",")
dat2009 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2009.csv", header=TRUE, sep=",")
dat2010 <- read.csv(file="PALSARwDEM-NLuzon-Classification-2010.csv", header=TRUE, sep=",")

# CASE 1: Polarisation

# Insert new standard variables for classification levels 1,2,3 for multi-year data

# Level1: land - water

# 2007
dat2007$LC1[dat2007$LCCode=="WNOW" | dat2007$LCCode=="WNRB" | dat2007$LCCode=="WNSS"] <- "WTR"
dat2007$LC1[dat2007$LCCode!="WNOW" & dat2007$LCCode!="WNRB" & dat2007$LCCode!="WNSS"] <- "LND"
# 2008
dat2008$LC1[dat2008$LCCode=="WNOW" | dat2008$LCCode=="WNRB" | dat2008$LCCode=="WNSS"] <- "WTR"
dat2008$LC1[dat2008$LCCode!="WNOW" & dat2008$LCCode!="WNRB" & dat2008$LCCode!="WNSS"] <- "LND"
# 2009
dat2009$LC1[dat2009$LCCode=="WNOW" | dat2009$LCCode=="WNRB" | dat2009$LCCode=="WNSS"] <- "WTR"
dat2009$LC1[dat2009$LCCode!="WNOW" & dat2009$LCCode!="WNRB" & dat2009$LCCode!="WNSS"] <- "LND"
# 2010
dat2010$LC1[dat2010$LCCode=="WNOW" | dat2010$LCCode=="WNRB" | dat2010$LCCode=="WNSS"] <- "WTR"
dat2010$LC1[dat2010$LCCode!="WNOW" & dat2010$LCCode!="WNRB" & dat2010$LCCode!="WNSS"] <- "LND"

# Level2: vegetation - non-vegetation

# 2007
dat2007$LC2[dat2007$LC1=="WTR"] <- "WTR"
dat2007$LC2[dat2007$LC1!="WTR" & dat2007$LCCode=="LNBU"] <- "NVG"
dat2007$LC2[dat2007$LC1!="WTR" & dat2007$LCCode!="LNBU"] <- "VEG"
# 2008
dat2008$LC2[dat2008$LC1=="WTR"] <- "WTR"
dat2008$LC2[dat2008$LC1!="WTR" & dat2008$LCCode=="LNBU"] <- "NVG"
dat2008$LC2[dat2008$LC1!="WTR" & dat2008$LCCode!="LNBU"] <- "VEG"
# 2009
dat2009$LC2[dat2009$LC1=="WTR"] <- "WTR"
dat2009$LC2[dat2009$LC1!="WTR" & dat2009$LCCode=="LNBU"] <- "NVG"
dat2009$LC2[dat2009$LC1!="WTR" & dat2009$LCCode!="LNBU"] <- "VEG"
# 2010
dat2010$LC2[dat2010$LC1=="WTR"] <- "WTR"
dat2010$LC2[dat2010$LC1!="WTR" & dat2010$LCCode=="LNBU"] <- "NVG"
dat2010$LC2[dat2010$LC1!="WTR" & dat2010$LCCode!="LNBU"] <- "VEG"

# Level3: forest - non-forest

# 2007
dat2007$LC3 <- "OOO"
dat2007$LC3[dat2007$LC2=="WTR"] <- "WTR"
dat2007$LC3[dat2007$LC2=="NVG"] <- "NVG"
dat2007$LC3[dat2007$LCCode=="LVGR" | dat2007$LCCode=="LVSH" | dat2007$LCCode=="LVWG"] <- "NFR"
dat2007$LC3[dat2007$LC3=="OOO"] <- "FOR"
# 2008
dat2008$LC3 <- "OOO"
dat2008$LC3[dat2008$LC2=="WTR"] <- "WTR"
dat2008$LC3[dat2008$LC2=="NVG"] <- "NVG"
dat2008$LC3[dat2008$LCCode=="LVGR" | dat2008$LCCode=="LVSH" | dat2008$LCCode=="LVWG"] <- "NFR"
dat2008$LC3[dat2008$LC3=="OOO"] <- "FOR"
# 2009
dat2009$LC3 <- "OOO"
dat2009$LC3[dat2009$LC2=="WTR"] <- "WTR"
dat2009$LC3[dat2009$LC2=="NVG"] <- "NVG"
dat2009$LC3[dat2009$LCCode=="LVGR" | dat2009$LCCode=="LVSH" | dat2009$LCCode=="LVWG"] <- "NFR"
dat2009$LC3[dat2009$LC3=="OOO"] <- "FOR"
# 2010
dat2010$LC3 <- "OOO"
dat2010$LC3[dat2010$LC2=="WTR"] <- "WTR"
dat2010$LC3[dat2010$LC2=="NVG"] <- "NVG"
dat2010$LC3[dat2010$LCCode=="LVGR" | dat2010$LCCode=="LVSH" | dat2010$LCCode=="LVWG"] <- "NFR"
dat2010$LC3[dat2010$LC3=="OOO"] <- "FOR"

# Insert new variables for remaining classification levels based on clustering dendrograms

# Level4: Node 8 Split

# 2007
dat2007$LC4 <- "OOO"
dat2007$LC4[dat2007$LC3=="WTR"] <- "WTR"
dat2007$LC4[dat2007$LC3=="NVG"] <- "NVG"
dat2007$LC4[dat2007$LC3=="NFR"] <- "NFR"
dat2007$LC4[dat2007$LCCode=="LVMG"] <- "MGF"
dat2007$LC4[dat2007$LC4=="OOO"] <- "FG7"
# 2008
dat2008$LC4 <- "OOO"
dat2008$LC4[dat2008$LC3=="WTR"] <- "WTR"
dat2008$LC4[dat2008$LC3=="NVG"] <- "NVG"
dat2008$LC4[dat2008$LC3=="NFR"] <- "NFR"
dat2008$LC4[dat2008$LCCode=="LVMG"] <- "MGF"
dat2008$LC4[dat2008$LC4=="OOO"] <- "FG7"
# 2009
dat2009$LC4 <- "OOO"
dat2009$LC4[dat2009$LC3=="WTR"] <- "WTR"
dat2009$LC4[dat2009$LC3=="NVG"] <- "NVG"
dat2009$LC4[dat2009$LC3=="NFR"] <- "NFR"
dat2009$LC4[dat2009$LCCode=="LVMG"] <- "MGF"
dat2009$LC4[dat2009$LC4=="OOO"] <- "FG7"
# 2010
dat2010$LC4 <- "OOO"
dat2010$LC4[dat2010$LC3=="WTR"] <- "WTR"
dat2010$LC4[dat2010$LC3=="NVG"] <- "NVG"
dat2010$LC4[dat2010$LC3=="NFR"] <- "NFR"
dat2010$LC4[dat2010$LCCode=="LVMG"] <- "MGF"
dat2010$LC4[dat2010$LC4=="OOO"] <- "FG7"

# Level5: Node 7 Split

# 2007
dat2007$LC5 <- "OOO"
dat2007$LC5[dat2007$LC4=="WTR"] <- "WTR"
dat2007$LC5[dat2007$LC4=="NVG"] <- "NVG"
dat2007$LC5[dat2007$LC4=="NFR"] <- "NFR"
dat2007$LC5[dat2007$LC4=="MGF"] <- "MGF"
dat2007$LC5[dat2007$LCCode=="FOFC"] <- "OFC"
dat2007$LC5[dat2007$LC5=="OOO"] <- "FG6"
# 2008
dat2008$LC5 <- "OOO"
dat2008$LC5[dat2008$LC4=="WTR"] <- "WTR"
dat2008$LC5[dat2008$LC4=="NVG"] <- "NVG"
dat2008$LC5[dat2008$LC4=="NFR"] <- "NFR"
dat2008$LC5[dat2008$LC4=="MGF"] <- "MGF"
dat2008$LC5[dat2008$LCCode=="FOFC"] <- "OFC"
dat2008$LC5[dat2008$LC5=="OOO"] <- "FG6"
# 2009
dat2009$LC5 <- "OOO"
dat2009$LC5[dat2009$LC4=="WTR"] <- "WTR"
dat2009$LC5[dat2009$LC4=="NVG"] <- "NVG"
dat2009$LC5[dat2009$LC4=="NFR"] <- "NFR"
dat2009$LC5[dat2009$LC4=="MGF"] <- "MGF"
dat2009$LC5[dat2009$LCCode=="FOFC"] <- "OFC"
dat2009$LC5[dat2009$LC5=="OOO"] <- "FG6"
# 2010
dat2010$LC5 <- "OOO"
dat2010$LC5[dat2010$LC4=="WTR"] <- "WTR"
dat2010$LC5[dat2010$LC4=="NVG"] <- "NVG"
dat2010$LC5[dat2010$LC4=="NFR"] <- "NFR"
dat2010$LC5[dat2010$LC4=="MGF"] <- "MGF"
dat2010$LC5[dat2010$LCCode=="FOFC"] <- "OFC"
dat2010$LC5[dat2010$LC5=="OOO"] <- "FG6"

# Level6: Node 6 Split

# 2007
dat2007$LC6 <- "OOO"
dat2007$LC6[dat2007$LC5=="WTR"] <- "WTR"
dat2007$LC6[dat2007$LC5=="NVG"] <- "NVG"
dat2007$LC6[dat2007$LC5=="NFR"] <- "NFR"
dat2007$LC6[dat2007$LC5=="MGF"] <- "MGF"
dat2007$LC6[dat2007$LC5=="OFC"] <- "OFC"
dat2007$LC6[dat2007$LCCode=="FCFB" | dat2007$LCCode=="FOFB"] <- "FG3"
dat2007$LC6[dat2007$LC6=="OOO"] <- "FG5"
# 2008
dat2008$LC6 <- "OOO"
dat2008$LC6[dat2008$LC5=="WTR"] <- "WTR"
dat2008$LC6[dat2008$LC5=="NVG"] <- "NVG"
dat2008$LC6[dat2008$LC5=="NFR"] <- "NFR"
dat2008$LC6[dat2008$LC5=="MGF"] <- "MGF"
dat2008$LC6[dat2008$LC5=="OFC"] <- "OFC"
dat2008$LC6[dat2008$LCCode=="FCFB" | dat2008$LCCode=="FOFB" | dat2008$LCCode=="FCFM"] <- "FG5"
dat2008$LC6[dat2008$LC6=="OOO"] <- "FG4"
# 2009
dat2009$LC6 <- "OOO"
dat2009$LC6[dat2009$LC5=="WTR"] <- "WTR"
dat2009$LC6[dat2009$LC5=="NVG"] <- "NVG"
dat2009$LC6[dat2009$LC5=="NFR"] <- "NFR"
dat2009$LC6[dat2009$LC5=="MGF"] <- "MGF"
dat2009$LC6[dat2009$LC5=="OFC"] <- "OFC"
dat2009$LC6[dat2009$LCCode=="FCFB"] <- "CFB"
dat2009$LC6[dat2009$LC6=="OOO"] <- "FG5"
# 2010
dat2010$LC6 <- "OOO"
dat2010$LC6[dat2010$LC5=="WTR"] <- "WTR"
dat2010$LC6[dat2010$LC5=="NVG"] <- "NVG"
dat2010$LC6[dat2010$LC5=="NFR"] <- "NFR"
dat2010$LC6[dat2010$LC5=="MGF"] <- "MGF"
dat2010$LC6[dat2010$LC5=="OFC"] <- "OFC"
dat2010$LC6[dat2010$LCCode=="FCFB" | dat2010$LCCode=="FOFB" | dat2010$LCCode=="FCFM"] <- "FG4"
dat2010$LC6[dat2010$LC6=="OOO"] <- "FG5"

# Level7: Node 5 Split

# 2007
dat2007$LC7 <- "OOO"
dat2007$LC7[dat2007$LC6=="WTR"] <- "WTR"
dat2007$LC7[dat2007$LC6=="NVG"] <- "NVG"
dat2007$LC7[dat2007$LC6=="NFR"] <- "NFR"
dat2007$LC7[dat2007$LC6=="MGF"] <- "MGF"
dat2007$LC7[dat2007$LC6=="OFC"] <- "OFC"
dat2007$LC7[dat2007$LC6=="FG3"] <- "FG3"
dat2007$LC7[dat2007$LCCode=="FCFM" | dat2007$LCCode=="FFPB"] <- "FG1"
dat2007$LC7[dat2007$LC7=="OOO"] <- "FG4"
# 2008
dat2008$LC7 <- "OOO"
dat2008$LC7[dat2008$LC6=="WTR"] <- "WTR"
dat2008$LC7[dat2008$LC6=="NVG"] <- "NVG"
dat2008$LC7[dat2008$LC6=="NFR"] <- "NFR"
dat2008$LC7[dat2008$LC6=="MGF"] <- "MGF"
dat2008$LC7[dat2008$LC6=="OFC"] <- "OFC"
dat2008$LC7[dat2008$LC6=="FG4"] <- "FG4"
dat2008$LC7[dat2008$LCCode=="FCFB"] <- "CFB"
dat2008$LC7[dat2008$LCCode=="FOFB" | dat2008$LCCode=="FCFM"] <- "FG1"
# 2009
dat2009$LC7 <- "OOO"
dat2009$LC7[dat2009$LC6=="WTR"] <- "WTR"
dat2009$LC7[dat2009$LC6=="NVG"] <- "NVG"
dat2009$LC7[dat2009$LC6=="NFR"] <- "NFR"
dat2009$LC7[dat2009$LC6=="MGF"] <- "MGF"
dat2009$LC7[dat2009$LC6=="OFC"] <- "OFC"
dat2009$LC7[dat2009$LC6=="CFB"] <- "CFB"
dat2009$LC7[dat2009$LCCode=="FFPC"] <- "FPC"
dat2009$LC7[dat2009$LC7=="OOO"] <- "FG4"
# 2010
dat2010$LC7 <- "OOO"
dat2010$LC7[dat2010$LC6=="WTR"] <- "WTR"
dat2010$LC7[dat2010$LC6=="NVG"] <- "NVG"
dat2010$LC7[dat2010$LC6=="NFR"] <- "NFR"
dat2010$LC7[dat2010$LC6=="MGF"] <- "MGF"
dat2010$LC7[dat2010$LC6=="OFC"] <- "OFC"
dat2010$LC7[dat2010$LC6=="FG4"] <- "FG4"
dat2010$LC7[dat2010$LCCode=="FFPC"] <- "FPC"
dat2010$LC7[dat2010$LC7=="OOO"] <- "FG3"

# Level8: Node 4 Split

# 2007
dat2007$LC8 <- "OOO"
dat2007$LC8[dat2007$LC7=="WTR"] <- "WTR"
dat2007$LC8[dat2007$LC7=="NVG"] <- "NVG"
dat2007$LC8[dat2007$LC7=="NFR"] <- "NFR"
dat2007$LC8[dat2007$LC7=="MGF"] <- "MGF"
dat2007$LC8[dat2007$LC7=="OFC"] <- "OFC"
dat2007$LC8[dat2007$LC7=="FG3"] <- "FG3"
dat2007$LC8[dat2007$LC7=="FG1"] <- "FG1"
dat2007$LC8[dat2007$LCCode=="FOFM"] <- "OFM"
dat2007$LC8[dat2007$LC8=="OOO"] <- "FG2"
# 2008
dat2008$LC8 <- "OOO"
dat2008$LC8[dat2008$LC7=="WTR"] <- "WTR"
dat2008$LC8[dat2008$LC7=="NVG"] <- "NVG"
dat2008$LC8[dat2008$LC7=="NFR"] <- "NFR"
dat2008$LC8[dat2008$LC7=="MGF"] <- "MGF"
dat2008$LC8[dat2008$LC7=="OFC"] <- "OFC"
dat2008$LC8[dat2008$LC7=="CFB"] <- "CFB"
dat2008$LC8[dat2008$LC7=="FG1"] <- "FG1"
dat2008$LC8[dat2008$LCCode=="FFPB" | dat2008$LCCode=="FOFM"] <- "FG2"
dat2008$LC8[dat2008$LC8=="OOO"] <- "FG3"
# 2009
dat2009$LC8 <- "OOO"
dat2009$LC8[dat2009$LC7=="WTR"] <- "WTR"
dat2009$LC8[dat2009$LC7=="NVG"] <- "NVG"
dat2009$LC8[dat2009$LC7=="NFR"] <- "NFR"
dat2009$LC8[dat2009$LC7=="MGF"] <- "MGF"
dat2009$LC8[dat2009$LC7=="OFC"] <- "OFC"
dat2009$LC8[dat2009$LC7=="CFB"] <- "CFB"
dat2009$LC8[dat2009$LC7=="FPC"] <- "FPC"
dat2009$LC8[dat2009$LCCode=="FCFM" | dat2009$LCCode=="FOFB"] <- "FG1"
dat2009$LC8[dat2009$LC8=="OOO"] <- "FG3"
# 2010
dat2010$LC8 <- "OOO"
dat2010$LC8[dat2010$LC7=="WTR"] <- "WTR"
dat2010$LC8[dat2010$LC7=="NVG"] <- "NVG"
dat2010$LC8[dat2010$LC7=="NFR"] <- "NFR"
dat2010$LC8[dat2010$LC7=="MGF"] <- "MGF"
dat2010$LC8[dat2010$LC7=="OFC"] <- "OFC"
dat2010$LC8[dat2010$LC7=="FPC"] <- "FPC"
dat2010$LC8[dat2010$LC7=="FG3"] <- "FG3"
dat2010$LC8[dat2010$LCCode=="FCFB"] <- "CFB"
dat2010$LC8[dat2010$LC8=="OOO"] <- "FG1"

# Level9: Node 3 Split

# 2007
dat2007$LC9 <- "OOO"
dat2007$LC9[dat2007$LC8=="WTR"] <- "WTR"
dat2007$LC9[dat2007$LC8=="NVG"] <- "NVG"
dat2007$LC9[dat2007$LC8=="NFR"] <- "NFR"
dat2007$LC9[dat2007$LC8=="MGF"] <- "MGF"
dat2007$LC9[dat2007$LC8=="OFC"] <- "OFC"
dat2007$LC9[dat2007$LC8=="OFM"] <- "OFM"
dat2007$LC9[dat2007$LC8=="FG1"] <- "FG1"
dat2007$LC9[dat2007$LC8=="FG2"] <- "FG2"
dat2007$LC9[dat2007$LCCode=="FCFB"] <- "CFB"
dat2007$LC9[dat2007$LCCode=="FOFB"] <- "OFB"
# 2008
dat2008$LC9 <- "OOO"
dat2008$LC9[dat2008$LC8=="WTR"] <- "WTR"
dat2008$LC9[dat2008$LC8=="NVG"] <- "NVG"
dat2008$LC9[dat2008$LC8=="NFR"] <- "NFR"
dat2008$LC9[dat2008$LC8=="MGF"] <- "MGF"
dat2008$LC9[dat2008$LC8=="OFC"] <- "OFC"
dat2008$LC9[dat2008$LC8=="CFB"] <- "CFB"
dat2008$LC9[dat2008$LC8=="FG1"] <- "FG1"
dat2008$LC9[dat2008$LC8=="FG2"] <- "FG2"
dat2008$LC9[dat2008$LCCode=="FFPC"] <- "FPC"
dat2008$LC9[dat2008$LCCode=="FCFC"] <- "CFC"
# 2009
dat2009$LC9 <- "OOO"
dat2009$LC9[dat2009$LC8=="WTR"] <- "WTR"
dat2009$LC9[dat2009$LC8=="NVG"] <- "NVG"
dat2009$LC9[dat2009$LC8=="NFR"] <- "NFR"
dat2009$LC9[dat2009$LC8=="MGF"] <- "MGF"
dat2009$LC9[dat2009$LC8=="OFC"] <- "OFC"
dat2009$LC9[dat2009$LC8=="CFB"] <- "CFB"
dat2009$LC9[dat2009$LC8=="FPC"] <- "FPC"
dat2009$LC9[dat2009$LC8=="FG1"] <- "FG1"
dat2009$LC9[dat2009$LCCode=="FCFC"] <- "CFC"
dat2009$LC9[dat2009$LC9=="OOO"] <- "FG2"
# 2010
dat2010$LC9 <- "OOO"
dat2010$LC9[dat2010$LC8=="WTR"] <- "WTR"
dat2010$LC9[dat2010$LC8=="NVG"] <- "NVG"
dat2010$LC9[dat2010$LC8=="NFR"] <- "NFR"
dat2010$LC9[dat2010$LC8=="MGF"] <- "MGF"
dat2010$LC9[dat2010$LC8=="OFC"] <- "OFC"
dat2010$LC9[dat2010$LC8=="FPC"] <- "FPC"
dat2010$LC9[dat2010$LC8=="CFB"] <- "CFB"
dat2010$LC9[dat2010$LC8=="FG1"] <- "FG1"
dat2010$LC9[dat2010$LCCode=="FOFM"] <- "OFM"
dat2010$LC9[dat2010$LC9=="OOO"] <- "FG2"

# Level10: Node 2 Split

# 2007
dat2007$LC10 <- "OOO"
dat2007$LC10[dat2007$LC9=="WTR"] <- "WTR"
dat2007$LC10[dat2007$LC9=="NVG"] <- "NVG"
dat2007$LC10[dat2007$LC9=="NFR"] <- "NFR"
dat2007$LC10[dat2007$LC9=="MGF"] <- "MGF"
dat2007$LC10[dat2007$LC9=="OFC"] <- "OFC"
dat2007$LC10[dat2007$LC9=="OFM"] <- "OFM"
dat2007$LC10[dat2007$LC9=="CFB"] <- "CFB"
dat2007$LC10[dat2007$LC9=="OFB"] <- "OFB"
dat2007$LC10[dat2007$LC9=="FG1"] <- "FG1"
dat2007$LC10[dat2007$LCCode=="FCFC"] <- "CFC"
dat2007$LC10[dat2007$LCCode=="FFPC"] <- "FPC"
# 2008
dat2008$LC10 <- "OOO"
dat2008$LC10[dat2008$LC9=="WTR"] <- "WTR"
dat2008$LC10[dat2008$LC9=="NVG"] <- "NVG"
dat2008$LC10[dat2008$LC9=="NFR"] <- "NFR"
dat2008$LC10[dat2008$LC9=="MGF"] <- "MGF"
dat2008$LC10[dat2008$LC9=="OFC"] <- "OFC"
dat2008$LC10[dat2008$LC9=="CFB"] <- "CFB"
dat2008$LC10[dat2008$LC9=="CFC"] <- "CFC"
dat2008$LC10[dat2008$LC9=="FPC"] <- "FPC"
dat2008$LC10[dat2008$LC9=="FG1"] <- "FG1"
dat2008$LC10[dat2008$LCCode=="FFPB"] <- "FPB"
dat2008$LC10[dat2008$LCCode=="FOFM"] <- "OFM"
# 2009
dat2009$LC10 <- "OOO"
dat2009$LC10[dat2009$LC9=="WTR"] <- "WTR"
dat2009$LC10[dat2009$LC9=="NVG"] <- "NVG"
dat2009$LC10[dat2009$LC9=="NFR"] <- "NFR"
dat2009$LC10[dat2009$LC9=="MGF"] <- "MGF"
dat2009$LC10[dat2009$LC9=="OFC"] <- "OFC"
dat2009$LC10[dat2009$LC9=="CFB"] <- "CFB"
dat2009$LC10[dat2009$LC9=="FPC"] <- "FPC"
dat2009$LC10[dat2009$LC9=="CFC"] <- "CFC"
dat2009$LC10[dat2009$LC9=="FG1"] <- "FG1"
dat2009$LC10[dat2009$LCCode=="FFPB"] <- "FPB"
dat2009$LC10[dat2009$LCCode=="FOFM"] <- "OFM"
# 2010
dat2010$LC10 <- "OOO"
dat2010$LC10[dat2010$LC9=="WTR"] <- "WTR"
dat2010$LC10[dat2010$LC9=="NVG"] <- "NVG"
dat2010$LC10[dat2010$LC9=="NFR"] <- "NFR"
dat2010$LC10[dat2010$LC9=="MGF"] <- "MGF"
dat2010$LC10[dat2010$LC9=="OFC"] <- "OFC"
dat2010$LC10[dat2010$LC9=="FPC"] <- "FPC"
dat2010$LC10[dat2010$LC9=="CFB"] <- "CFB"
dat2010$LC10[dat2010$LC9=="OFM"] <- "OFM"
dat2010$LC10[dat2010$LC9=="FG1"] <- "FG1"
dat2010$LC10[dat2010$LCCode=="FCFC"] <- "CFC"
dat2010$LC10[dat2010$LCCode=="FFPB"] <- "FPB"

# Level11: Node 1 Split

# 2007
dat2007$LC11 <- "OOO"
dat2007$LC11[dat2007$LC10=="WTR"] <- "WTR"
dat2007$LC11[dat2007$LC10=="NVG"] <- "NVG"
dat2007$LC11[dat2007$LC10=="NFR"] <- "NFR"
dat2007$LC11[dat2007$LC10=="MGF"] <- "MGF"
dat2007$LC11[dat2007$LC10=="OFC"] <- "OFC"
dat2007$LC11[dat2007$LC10=="OFM"] <- "OFM"
dat2007$LC11[dat2007$LC10=="CFB"] <- "CFB"
dat2007$LC11[dat2007$LC10=="OFB"] <- "OFB"
dat2007$LC11[dat2007$LC10=="CFC"] <- "CFC"
dat2007$LC11[dat2007$LC10=="FPC"] <- "FPC"
dat2007$LC11[dat2007$LCCode=="FCFM"] <- "CFM"
dat2007$LC11[dat2007$LCCode=="FFPB"] <- "FPB"
# 2008
dat2008$LC11 <- "OOO"
dat2008$LC11[dat2008$LC10=="WTR"] <- "WTR"
dat2008$LC11[dat2008$LC10=="NVG"] <- "NVG"
dat2008$LC11[dat2008$LC10=="NFR"] <- "NFR"
dat2008$LC11[dat2008$LC10=="MGF"] <- "MGF"
dat2008$LC11[dat2008$LC10=="OFC"] <- "OFC"
dat2008$LC11[dat2008$LC10=="CFB"] <- "CFB"
dat2008$LC11[dat2008$LC10=="CFC"] <- "CFC"
dat2008$LC11[dat2008$LC10=="FPC"] <- "FPC"
dat2008$LC11[dat2008$LC10=="FPB"] <- "FPB"
dat2008$LC11[dat2008$LC10=="OFM"] <- "OFM"
dat2008$LC11[dat2008$LCCode=="FOFB"] <- "OFB"
dat2008$LC11[dat2008$LCCode=="FCFM"] <- "CFM"
# 2009
dat2009$LC11 <- "OOO"
dat2009$LC11[dat2009$LC10=="WTR"] <- "WTR"
dat2009$LC11[dat2009$LC10=="NVG"] <- "NVG"
dat2009$LC11[dat2009$LC10=="NFR"] <- "NFR"
dat2009$LC11[dat2009$LC10=="MGF"] <- "MGF"
dat2009$LC11[dat2009$LC10=="OFC"] <- "OFC"
dat2009$LC11[dat2009$LC10=="CFB"] <- "CFB"
dat2009$LC11[dat2009$LC10=="FPC"] <- "FPC"
dat2009$LC11[dat2009$LC10=="CFC"] <- "CFC"
dat2009$LC11[dat2009$LC10=="FPB"] <- "FPB"
dat2009$LC11[dat2009$LC10=="OFM"] <- "OFM"
dat2009$LC11[dat2009$LCCode=="FOFB"] <- "OFB"
dat2009$LC11[dat2009$LCCode=="FCFM"] <- "CFM"
# 2010
dat2010$LC11 <- "OOO"
dat2010$LC11[dat2010$LC10=="WTR"] <- "WTR"
dat2010$LC11[dat2010$LC10=="NVG"] <- "NVG"
dat2010$LC11[dat2010$LC10=="NFR"] <- "NFR"
dat2010$LC11[dat2010$LC10=="MGF"] <- "MGF"
dat2010$LC11[dat2010$LC10=="OFC"] <- "OFC"
dat2010$LC11[dat2010$LC10=="FPC"] <- "FPC"
dat2010$LC11[dat2010$LC10=="CFB"] <- "CFB"
dat2010$LC11[dat2010$LC10=="OFM"] <- "OFM"
dat2010$LC11[dat2010$LC10=="CFC"] <- "CFC"
dat2010$LC11[dat2010$LC10=="FPB"] <- "FPB"
dat2010$LC11[dat2010$LCCode=="FCFM"] <- "CFM"
dat2010$LC11[dat2010$LCCode=="FOFB"] <- "OFB"

# Select observations per classification level and store selected data in variables

# 2007
dat2007.lc1  <- dat2007
dat2007.lc2  <- subset(dat2007, subset=(LC1=="LND"))
dat2007.lc3  <- subset(dat2007, subset=(LC2=="VEG"))
dat2007.lc4  <- subset(dat2007, subset=(LC3=="FOR"))
dat2007.lc5  <- subset(dat2007, subset=(LC4=="FG7"))
dat2007.lc6  <- subset(dat2007, subset=(LC5=="FG6"))
dat2007.lc7  <- subset(dat2007, subset=(LC6=="FG5"))
dat2007.lc8  <- subset(dat2007, subset=(LC7=="FG4"))
dat2007.lc9  <- subset(dat2007, subset=(LC8=="FG3"))
dat2007.lc10 <- subset(dat2007, subset=(LC9=="FG2"))
dat2007.lc11 <- subset(dat2007, subset=(LC10=="FG1"))

# Execute tree function using specified classification level and predictor variables

# 2007
tree2007.lc1  <- tree(factor(LC1)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT, dat2007.lc1)
tree2007.lc2  <- tree(factor(LC2)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT, dat2007.lc2)
tree2007.lc3  <- tree(factor(LC3)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT, dat2007.lc3)
tree2007.lc4  <- tree(factor(LC4)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT, dat2007.lc4)
tree2007.lc5  <- tree(factor(LC5)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT, dat2007.lc5)
tree2007.lc6  <- tree(factor(LC6)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT, dat2007.lc6)
tree2007.lc7  <- tree(factor(LC7)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT, dat2007.lc7)
tree2007.lc8  <- tree(factor(LC8)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT, dat2007.lc8)
tree2007.lc9  <- tree(factor(LC9)  ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT, dat2007.lc9)
tree2007.lc10 <- tree(factor(LC10) ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT, dat2007.lc10)
tree2007.lc11 <- tree(factor(LC11) ~ MeanHH + MeanHV + MeanRAT + SDHH + SDHV + SDRAT, dat2007.lc11)

# Generate tree summary and misclassification statistics and save as TXT file

# 2007
sink("output-2007-tree-summary-lc1.txt", append=FALSE, split=TRUE)
print(tree2007.lc1)
print(summary(tree2007.lc1))
print(misclass.tree(tree2007.lc1, detail=TRUE))
sink()
sink("output-2007-tree-summary-lc2.txt", append=FALSE, split=TRUE)
print(tree2007.lc2)
print(summary(tree2007.lc2))
print(misclass.tree(tree2007.lc2, detail=TRUE))
sink()
sink("output-2007-tree-summary-lc3.txt", append=FALSE, split=TRUE)
print(tree2007.lc3)
print(summary(tree2007.lc3))
print(misclass.tree(tree2007.lc3, detail=TRUE))
sink()
sink("output-2007-tree-summary-lc4.txt", append=FALSE, split=TRUE)
print(tree2007.lc4)
print(summary(tree2007.lc4))
print(misclass.tree(tree2007.lc4, detail=TRUE))
sink()
sink("output-2007-tree-summary-lc5.txt", append=FALSE, split=TRUE)
print(tree2007.lc5)
print(summary(tree2007.lc5))
print(misclass.tree(tree2007.lc5, detail=TRUE))
sink()
sink("output-2007-tree-summary-lc6.txt", append=FALSE, split=TRUE)
print(tree2007.lc6)
print(summary(tree2007.lc6))
print(misclass.tree(tree2007.lc6, detail=TRUE))
sink()
sink("output-2007-tree-summary-lc7.txt", append=FALSE, split=TRUE)
print(tree2007.lc7)
print(summary(tree2007.lc7))
print(misclass.tree(tree2007.lc7, detail=TRUE))
sink()
sink("output-2007-tree-summary-lc8.txt", append=FALSE, split=TRUE)
print(tree2007.lc8)
print(summary(tree2007.lc8))
print(misclass.tree(tree2007.lc8, detail=TRUE))
sink()
sink("output-2007-tree-summary-lc9.txt", append=FALSE, split=TRUE)
print(tree2007.lc9)
print(summary(tree2007.lc9))
print(misclass.tree(tree2007.lc9, detail=TRUE))
sink()
sink("output-2007-tree-summary-lc10.txt", append=FALSE, split=TRUE)
print(tree2007.lc10)
print(summary(tree2007.lc10))
print(misclass.tree(tree2007.lc10, detail=TRUE))
sink()
sink("output-2007-tree-summary-lc11.txt", append=FALSE, split=TRUE)
print(tree2007.lc11)
print(summary(tree2007.lc11))
print(misclass.tree(tree2007.lc11, detail=TRUE))
sink()

# Plot tree object and save as PNG file

# 2007
png("output-2007-tree-lc1.png", width=700, height=500)
plot(tree2007.lc1)
text(tree2007.lc1, cex=0.70)
dev.off()
png("output-2007-tree-lc2.png", width=700, height=500)
plot(tree2007.lc2)
text(tree2007.lc2, cex=0.70)
dev.off()
png("output-2007-tree-lc3.png", width=700, height=500)
plot(tree2007.lc3)
text(tree2007.lc3, cex=0.70)
dev.off()
png("output-2007-tree-lc4.png", width=700, height=500)
plot(tree2007.lc4)
text(tree2007.lc4, cex=0.70)
dev.off()
png("output-2007-tree-lc5.png", width=700, height=500)
plot(tree2007.lc5)
text(tree2007.lc5, cex=0.70)
dev.off()
png("output-2007-tree-lc6.png", width=700, height=500)
plot(tree2007.lc6)
text(tree2007.lc6, cex=0.70)
dev.off()
png("output-2007-tree-lc7.png", width=700, height=500)
plot(tree2007.lc7)
text(tree2007.lc7, cex=0.70)
dev.off()
png("output-2007-tree-lc8.png", width=700, height=500)
plot(tree2007.lc8)
text(tree2007.lc8, cex=0.70)
dev.off()
png("output-2007-tree-lc9.png", width=700, height=500)
plot(tree2007.lc9)
text(tree2007.lc9, cex=0.70)
dev.off()
png("output-2007-tree-lc10.png", width=700, height=500)
plot(tree2007.lc10)
text(tree2007.lc10, cex=0.70)
dev.off()
png("output-2007-tree-lc11.png", width=700, height=500)
plot(tree2007.lc11)
text(tree2007.lc11, cex=0.70)
dev.off()

# Plot cross-validation graph and save as PNG file
png("output-2007-cv-lc1.png", width=700, height=500)
plot(cv.tree(tree2007.lc1))
dev.off()
png("output-2007-cv-lc2.png", width=700, height=500)
plot(cv.tree(tree2007.lc2))
dev.off()
png("output-2007-cv-lc3.png", width=700, height=500)
plot(cv.tree(tree2007.lc3))
dev.off()
png("output-2007-cv-lc4.png", width=700, height=500)
plot(cv.tree(tree2007.lc4))
dev.off()
png("output-2007-cv-lc5.png", width=700, height=500)
plot(cv.tree(tree2007.lc5))
dev.off()
png("output-2007-cv-lc6.png", width=700, height=500)
plot(cv.tree(tree2007.lc6))
dev.off()
png("output-2007-cv-lc7.png", width=700, height=500)
plot(cv.tree(tree2007.lc7))
dev.off()
png("output-2007-cv-lc8.png", width=700, height=500)
plot(cv.tree(tree2007.lc8))
dev.off()
png("output-2007-cv-lc9.png", width=700, height=500)
plot(cv.tree(tree2007.lc9))
dev.off()
png("output-2007-cv-lc10.png", width=700, height=500)
plot(cv.tree(tree2007.lc10))
dev.off()
png("output-2007-cv-lc11.png", width=700, height=500)
plot(cv.tree(tree2007.lc11))
dev.off()
